In [ ]:
import numpy as np

## Determinant

In [ ]:
# Generate 5 random points in 3D
v1 = np.random.rand(5,3)
v2 = np.random.rand(5,3)
v3 = np.random.rand(5,3)

# Compute the determinant of the matrix formed by the vectors (v1, v2, v3) for each row
# The determinant is zero if the vectors are coplanar
cross = np.cross(v2, v3)


dets = np.sum(v1 * cross, axis=1)
print(f"Full Determiant : {dets}")
print(f"Det 0 : {np.linalg.det(np.array([v2[0], v3[0], v1[0]]))}")
print(f"Det 1 : {np.linalg.det(np.array([v2[1], v3[1], v1[1]]))}")
print(f"Det 2 : {np.linalg.det(np.array([v2[2], v3[2], v1[2]]))}")

## $v_{ij} \cdot (v_{ik} \times \partial e_c)*det2$

In [ ]:
import numpy as np
import time

# Define the size of the matrices and vectors
n = 800  # Large number of rows
m = 3  # Number of columns
T = 200  # Number of repetitions

# Initialize variables to store total elapsed times
total_time_1 = 0
total_time_2 = 0


for t in range(T):
    # Generate random matrices and vectors
    eik = np.random.rand(n, m)
    derx = np.zeros((n, m))
    derx[:, 0] = 1
    nc = np.random.rand(n)

    print("init eik: \n", eik[:5])

    # Benchmark the first approach
    start_time = time.time()
    eikXdec_x_1 = np.cross(eik, derx) / nc[:, None]
    elapsed_time_1 = time.time() - start_time

    # Benchmark the second approach
    start_time = time.time()
    eikXdec_x_2 = eik[:, [0, 2, 1]] / nc[:, None]
    eikXdec_x_2[:, 0] = 0
    eikXdec_x_2[:, 1] *= -1  
    eikXdec_x_2 *= -1
    elapsed_time_2 = time.time() - start_time

    total_time_1 += elapsed_time_1
    total_time_2 += elapsed_time_2

    print("final eik: \n", eik[:5])
    print("*-----------------------------*")

    # asssert same
    assert(np.allclose(eikXdec_x_1, eikXdec_x_2))
    
total_time_1 /= T
total_time_2 /= T

# Print the elapsed times
print("Elapsed time for approach 1:", total_time_1, "seconds")
print("Elapsed time for approach 2:", total_time_2, "seconds")

In [ ]:
# 5 Random points
v1 = np.random.rand(5,3)
# 3 random faces indices
f1 = np.random.randint(0, 5, 3)

np.sum(v1[f1], axis=1)

In [ ]:
import numpy as np

n= 5
m= 6
J = np.zeros((n,m))
v = np.ones(3)
J[2:n, 3: 6] = v * np.eye(3)
print(J)

J[:3, 0:3] = np.diag(v)
print(J)


In [ ]:
import numpy as np
import time

n= 8
m= 8

J = np.repeat([0,1,2,3,4,5,6,7,8], 9).reshape((9,9)).T
i = 3*np.array([1, 2, 0, 1, 2, 0, 1, 2])
v = np.array([10, 20, 30, 10, 40, 50, 60, 2])
J[range(m), i] = v
print(J)

In [ ]:
def cross_id(v, coord, type=0):
    """ Function tha retunr the cross product with coordinate vectors like [1, 0, 0], [0, 1, 0], [0, 0, 1]
        type 0
        V x [1,0,0]
        type 1
        [1,0,0] x V

    """

    if coord=='x':
        cross = v[:, [0, 2, 1]] 
        cross[:, 0] = 0
        cross[:, 2] *= -1 
    elif coord=='y':
        cross = v[:, [2, 1, 0]]
        cross[:, 0] *= -1
        cross[:, 1] = 0
    elif coord=='z':
        cross = v[:, [1, 0, 2]]
        cross[:, 1] *= -1
        cross[:, 2] = 0
    
    if type==1:
        cross *= -1

    return cross

In [ ]:
v = np.random.rand(1000000, 3)

# Test time
id_time = 0
cross_time = 0
for i in range(500):
    s = time.time()
    id_c =  cross_id(v/3, 'x', 1)
    id_time += time.time() - s

    s = time.time()
    cr = np.cross(np.array([1, 0, 0]),v/3)
    cross_time += time.time() - s

    assert(np.allclose(id_c, cr))

print("average id_time: ", id_time/100)

print("average cross_time: ", cross_time/100)


In [ ]:
# Compute the edge vectors per each face
n = 4
vj = np.array([[1, 1,1], [2, 2,2], [3, 3,3], [4, 4,4]])
vi = np.array([[0, 1,0], [0, 0,0], [0, 0,0], [0, 0,0]])
vk = np.array([[10, 10, 10], [20, 20,20], [30, 30,30], [40, 40,40]])
fvij = np.empty((n, 2, 3), dtype=float)

# Compute the edge vectors per each face
fvij[:,0] = vj - vi
fvij[:,1] = vk - vi
print(fvij[:,0])

In [ ]:
np.sum( np.array([1,0,1])*vj, axis=1)

In [ ]:
import numpy as np
face = np.array([0,3,5,1])
n = 6
m = 10
nli = 3
ei = np.array([[1,0,0],[0,1,0],[0,0,1]])
f = 1
ni = np.array([[1,2,3],[10,11,12],[4,5,6],[3,5,7]])
norms = np.array([[1,2,3,4],[5,6,7,8]])
J = np.zeros((n,m))

i = 1


J[range(i,i + len(face)), nli + face] = -np.sum( ei[f]*ni, axis=1)/norms[0, None]

print(J,-np.sum( ei[f]*ni, axis=1)/norms[0, None])

In [ ]:
import time 
import numpy as np

n = 1000
m = 1000
J = np.zeros((n,m))

a = 20
b = a*3
nt = np.random.randint(0, n, a)
v  = np.arange(0, b)
v1 = np.arange(0, b).reshape((20, 3))


tm  = 0
tm1 = 0
for i in range(1000):
    vals = np.random.rand(20,3)
    
    
    tic = time.time()
    J [nt.repeat(3), v] = vals.flatten()
    tm += time.time() - tic

    tic = time.time()
    J[nt, v1[:,0]] = vals[:,0]
    J[nt, v1[:,1]] = vals[:,1]
    J[nt, v1[:,2]] = vals[:,2]
    tm1 += time.time() - tic


tm /= 1000
tm1 /= 1000
print("tm: ", tm)
print("tm1: ", tm1)


In [ ]:
# Test construction of sparse matrix

# 1) Create a normal matrix J and then convert it to csc_matrix


import numpy as np
import time
from scipy.sparse import csc_matrix, coo_matrix
# Measure memory usage
import psutil


n = 1000
m = 2000

time_normal = 0
time_coo = 0
time_csc = 0
time_hess_coo = 0
time_hess_csc = 0

for _ in range(200):

    
    # Random columns
    cols = np.random.randint(0, m, 200)
    # Random rows
    rows = np.random.randint(0, n, 200)

    # Random values
    vals = np.random.rand(200)


    # Fill the matrix normal
    # Take time and memory usage
    tic = time.time()
    
    J = np.zeros((n,m))
    J[rows, cols] = vals
    J_sparse = csc_matrix(J)
    
    toc = time.time()

    
    time_normal += toc - tic


    # Fill the matrix csc
    tic = time.time()
    J_sparse_csc = csc_matrix((vals, (rows, cols)), shape=(n, m))
    toc = time.time()

    time_csc += toc - tic

    tic = time.time()
    h = (J_sparse_csc.T * J_sparse_csc).tocsr()
    toc = time.time()

    time_hess_csc = toc - tic

    # Fill matrix coo
    tic = time.time()
    J_sparse_coo = coo_matrix((vals, (rows, cols)), shape=(n, m))
    toc = time.time()

    time_coo += toc - tic

    tic = time.time()
    h = (J_sparse_coo.T * J_sparse_coo).tocsr()
    toc = time.time()

    time_hess_coo = toc - tic
    

time_normal /= 1000
time_coo /= 1000
time_csc /= 1000
time_hess_coo /= 1000
time_hess_csc /= 1000

print(f"time_normal:  {time_normal}\t mem_normal : {mem_normal}" )
print("time_csc: ", time_csc)
print("time_coo: ", time_coo)
print("time_hess_coo: ", time_hess_coo)
print("time_hess_csc: ", time_hess_csc)



In [ ]:
# Test speed hstack with append

import numpy as np
import time

n = 200
m = 300

i = []
v = np.array([])

append_time = 0
stac_time = 0
for _ in range(100):
    i = []
    v = np.array([])
    tic = time.time()
    for _ in range(n):
        a = np.random.randint(10, 100)
        # concatenate
        i.extend(np.random.randint(0, 100, a))
    i = np.array(i)
    toc = time.time()


    append_time += toc - tic

    tic = time.time()
    for _ in range(n):
        a = np.random.randint(10, 100)
        v = np.hstack((v, np.random.randint(0, 100, a)))
    toc = time.time()

    stac_time += toc - tic

append_time += toc - tic

append_time /= 100
stac_time /= 100

print("append_time: ", append_time)
print("stac_time: ", stac_time)


In [ ]:
print(i)

In [ ]:

import numpy as np
from scipy.sparse import csc_matrix

# Sample data
face = [0, 1, 2, 3, 4, 5, 6, 7]
f = 2
cij = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
# Calculate the row indices (i)
i_indices = np.arange(len(face))

# Calculate the column indices (j)
j_indices = 3 * f + np.arange(3)

# Create the index grid using broadcasting
i_grid, j_grid = np.meshgrid(i_indices, j_indices, indexing='ij')

# Calculate the values using cij
val = cij[:, j_indices - 3 * f][i_indices]

# Create the CSC matrix using the calculated data
shape = (len(face), 3 * (f + 1))
J = csc_matrix((val, (i_grid, j_grid)), shape=shape)

# Print the resulting CSC matrix
print(J.toarray())


In [ ]:
# Uncurry function 
X = np.arange(0,50)

indx = {"a": np.arange(0,10),
        "b": np.arange(10,20),
        "c": np.arange(20,30),
        }

def uncurry(X, v_idx):

    return [X[indx[k]] for k in v_idx]

a, b = uncurry(X, ["a", "b"])

print(a)
print(b)


In [ ]:
f=3
# Repeat the face indices 3 times [f1 f2 f3 f1 f2 f3 f1 f2 f3]
l = np.arange(3*f, 3*(f+1))
np.tile(l,3)

In [ ]:
import numpy as np

# Define the set of indices v
v = np.arange(0, 100)

# Define the list of indices f
f = [2, 4, 1, 6]

# Calculate the positions to extract and flatten the result
positions = np.array(f) * 3


# Create an array of indices to extract using NumPy's fancy indexing
indices_to_extract = np.repeat(positions, 3) + np.tile(np.arange(3), len(f))

print(f"positions: {positions}")
print(f"repeart : {np.repeat(positions, 3)}")
print(f"tile : {np.tile(np.arange(3), len(f))}")
print(f"indices_to_extract : {indices_to_extract}")
# Extract the values from v using fancy indexing
result = v[indices_to_extract]

print(result)


In [ ]:
v = np.random.randint(0, 4, (4,3))

nf = np.array([0, 1, 2])

print(f" nf.v0: {nf@v[0]} \n nf.v1: {nf@v[1]} \n nf.v2: {nf@v[2]} \n nf.v3: {nf@v[3]} \n nf.v = {np.sum(nf*v, axis=1)}")


In [ ]:
import numpy as np
from functools import reduce

v_idx = [[1,2],[3,4,5],[6,1,2,3],[1,2]]
c_v = [0, 1, 2, 3]

def concat(acc, ell):
    return np.hstack((acc, ell))

new_c = reduce( concat, [np.array([c_v[i]]).repeat(len(v_idx[i])) for i in range(len(v_idx)) ], np.array([]))

new_c

In [ ]:
import numpy as np

v_idx = [[1, 2], [3, 4, 5], [6, 1, 2, 3], [1, 2]]
c_v = [0, 1, 2, 3]

# Create a list of repeated values from c_v based on v_idx
repeated_values = [np.array([c_v[i]] * len(sublist)) for i, sublist in enumerate(v_idx)]

# Concatenate the repeated values using numpy.concatenate
new_c = np.concatenate(repeated_values)

print(new_c)


In [ ]:
import vedo as vd 

vd.settings.default_backend = 'k3d'

# Create a sphere
sphere = vd.Sphere(pos=(0, 0, 0), r=1, c='r')

# Create a plane (defined by a point on the plane and its normal vector)
plane = vd.Plane(
    pos=(0, 0, 0),
    normal=(0, 0, 1),
    s=(10, 10),
    res=(1, 1),
    c='gray5',
    alpha=0.8
)
# Cut the sphere with the plane

cut_sphere = sphere.cut_with_plane( origin=(0, 0, 0), normal=(0, 0, 1))
#cut_sphere2 = sphere.cut_with_plane( origin=(0, 0, 0), normal=(0, 0, 1), invert=True)


# Create a spline from the intersection points
#spline = vd.Spline(cut_sphere).c('blue').lw(5)

# Show the cut sphere and spline
vd.show(sphere, plane, axes=1)

In [ ]:
import numpy as np
# Given vector v
v = np.array([1, 3, 4, 2])

# Efficient generation of u
base_range = np.arange(3)
u = 3 * np.repeat(v, 3) + np.tile(base_range, len(v))
print(u)

In [ ]:
v = np.array([0,1,2,3,4,5])
np.tile(v, 3)

In [ ]:
import numpy as np

# Example lists of vertices
v0 = [[1,0,0],[0,1,0],[0,0,1]]
v1 = [[2,0,2],[2,2,0],[0,2,2]]
v2 = [[0,0,3],[1,0,1],[2,1,10]]

# Convert lists to numpy arrays
v0_array = np.array(v0)
v1_array = np.array(v1)
v2_array = np.array(v2)

# Create list of matrices
matrices = [np.vstack((v0_array[i], v1_array[i], v2_array[i])) for i in range(len(v0_array))]

# Display one of the matrices as an example
print(matrices[0])
print(matrices[1])
print(matrices[2])


In [ ]:
i = np.array([0, 3, 4])

indices = 3 * np.repeat(i, 3) + np.tile(range(3), len(i))
print(i)
print(indices)

In [ ]:
nc = np.array([[0,1,0]])

x  = np.array([[1,0,0], [0,1,0], [0,0,2]])  

f = np.array([0,2])
print(np.linalg.norm(np.array([1,-1,0])))
print(np.linalg.norm(np.array([0,1,-2])))
np.linalg.norm(nc - x[f], axis=1)


In [ ]:
import os 
import sys

# Add hananLab to path
#path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(os.getcwd()))))
path = os.path.dirname(os.getcwd())
sys.path.append(path)

import igl
import polyscope as ps
import numpy as np


from hanan.geometry.mesh import Mesh
from hanan.geometry.utils import *
from hanan.optimization.Sphericity import Sphericity
from hanan.optimization.Optimizer import Optimizer
from hanan.optimization.LineCong import LineCong
from hanan.optimization.LineCong_Fairness import LineCong_Fair
from hanan.optimization.Torsal import Torsal

# Define paths
dir_path = os.getcwd()
data_path = dir_path+"/approximation/data/" # data path

# Load test mesh
v, f = igl.read_triangle_mesh(os.path.join(data_path, "New_Tri_mesh.obj"))

n = igl.per_vertex_normals(v, f)

# Create mesh
mesh = Mesh()
mesh.make_mesh(v, f)

# Compute mesh properties
dual_top          = mesh.vertex_ring_faces_list()
inner_vertices    = mesh.inner_vertices()
vertex_adj        = mesh.vertex_adjacency_list()
boundary_faces    = mesh.boundary_faces()
boundary_vertices = mesh.boundary_vertices()
inner_edges       = mesh.inner_edges()

# Get vertex indices of each edge
ed_i, ed_j = mesh.edge_vertices()

# Get oposite vertex indices of each edge
ed_k, ed_l = mesh.edge_oposite_vertices()


# Fix direction
signs = np.sign(np.sum(n * ([0,0,-1]), axis=1))
n = n * signs[:, None]

# compute line congruence
e = 10 * n

# Compute second envelope
vv = v + e

# Compute indices of vertices of each face
i, j, k = f[:,0], f[:,1], f[:,2]


# Compute guess for sphere
ct, _, nt = circle_3pts(v[i], v[j], v[k])
ct2, _, nt2 = circle_3pts(vv[i], vv[j], vv[k])


for bf in boundary_faces:
    for bv in f[bf]:
        if bv in boundary_vertices:
            n[bv] = nt[bf]
            np.delete(boundary_vertices, np.where(boundary_vertices == bv))


vc  = np.sum(v[f], axis=1)/3
vvc = np.sum(vv[f], axis=1)/3


# Compute sphere center
signs = np.sign(np.sum(nt * ([0,0,-1]), axis=1))
nt = nt * signs[:, None]

sph_c = ct + 0.5*np.linalg.norm(ct2 - ct,axis=1)[:,None]*nt


# Compute sphere radius
sph_r = np.linalg.norm(sph_c - v[i], axis=1)

# Compute number of variables
nV = len(v)
nF = len(f)
nIE = len(inner_edges)


# Define variable indices
var_idx = {     "e"     : np.arange( 0            , 3*nV),  # Line congruence
                "sph_c" : np.arange( 3*nV         , 3*nV +  3*nF),  # Sphere centers
                "sph_r" : np.arange( 3*nV +  3*nF , 3*nV +  4*nF),  # Sphere radius
                "th"    : np.arange( 3*nV +  4*nF , 3*nV +  5*nF),  # theta  angle <t1, vji
                "phi"   : np.arange( 3*nV +  5*nF , 3*nV +  6*nF),  # phi  angel < t1, t2
                "nt1"   : np.arange( 3*nV +  6*nF , 3*nV +  9*nF),  # Normal torsal plane t1 
                "nt2"   : np.arange( 3*nV +  9*nF , 3*nV +  12*nF),  # Normal torsal plane t2
                "u"     : np.arange( 3*nV +  12*nF , 3*nV + 12*nF + 3*nIE)  # Normal torsal plane t2
        }

# Init X 
X = np.zeros(sum(len(arr) for arr in var_idx.values()))

X[var_idx["e"]]      = e.flatten()
X[var_idx["sph_c"]]  = sph_c.flatten()
X[var_idx["sph_r"]]  = sph_r

t1, t2, a1, a2, b, validity = solve_torsal(v[i], v[j], v[k] , e[i], e[j], e[k])

tt1 = unit(a1[:,None]*(vv[j] - vv[i]) + b[:,None]*(vv[k] - vv[i]))
tt2 = unit(a2[:,None]*(vv[j] - vv[i]) + b[:,None]*(vv[k] - vv[i]))

ec = np.sum(e[f], axis=1)/3

# Init Sphericity
sphericity = Sphericity()
sphericity.initialize_constraint(X, var_idx, f, v)

# Init Line Congruence Fairnes
line_fair = LineCong_Fair()
line_fair.initialize_constraint(X, var_idx, vertex_adj, inner_vertices) 
line_fair.set_weigth(0.001)

# Init Line Cong
linecong = LineCong()
linecong.initialize_constraint(X, var_idx, len(v),  dual_top, inner_vertices)

# Init Torsal 
torsal = Torsal()
torsal.initialize_constraint(X, var_idx, v, f)

#  Optimizer
optimizer = Optimizer()
optimizer.initialize_optimizer(X, var_idx, "LM", 0.5, 1)


it = 60
for _ in range(it):
    optimizer.unitize_variable("nt1", 3)
    optimizer.unitize_variable("nt2", 3)
    
    optimizer.get_gradients(sphericity)
    optimizer.get_gradients(linecong)
    optimizer.get_gradients(torsal)
    optimizer.get_gradients(line_fair)
    optimizer.optimize()






In [ ]:
## Extract variables
ne, nc, nr, th, phi = optimizer.uncurry_X("e", "sph_c", "sph_r", "th", "phi")

ne = ne.reshape((-1,3))
nc = nc.reshape((-1,3))

vv = v + ne
i, j, k = f[:,0], f[:,1], f[:,2]
vi, vj, vk = v[i], v[j], v[k]

vij = vj - vi 
vki = vk - vi

t1 = unit( np.cos(th)[:,None]*vij +  np.sin(th)[:,None]*vki)
t2 = unit(np.cos(th + phi)[:,None]*vij + np.sin(th + phi)[:,None]*vki)

tt1 = unit( np.cos(th)[:,None]*(vv[j] - vv[i]) +  np.sin(th)[:,None]*(vv[k] - vv[i]))
tt2 = unit(np.cos(th + phi)[:,None]*(vv[j] - vv[i]) + np.sin(th + phi)[:,None]*(vv[k] - vv[i]))

# Compute planarity
planarity1 = planarity_check(t1, tt1, ec)

planarity2 = planarity_check(t2, tt2, ec)

avg_planarity = (planarity1 + planarity2)/2
## Visualize
ps.init()
ps.remove_all_structures()

# Show boundary spheres
for id in range(len(boundary_faces)):
    i = boundary_faces[id]
    c = nc[i] 
    sphere = ps.register_point_cloud(f"sphere_c{i}", np.array([c]), enabled=True, color=(0,0,0), transparency=0.5)
    sphere.set_radius(nr[i], relative=False)



ps.register_point_cloud("cr", ct, enabled=True, radius=0.001, color=(0,0,0))
mesh = ps.register_surface_mesh("mesh", v, f)
mesh2 = ps.register_surface_mesh("mesh 2", vv, f)
mesh.add_vector_quantity("n", ne, length=1, enabled=True, vectortype="ambient", radius=0.0005, color=(0,0,0))


# Show sphere circumcircle axis
#mesh.add_vector_quantity(  "n",   nt, defined_on="faces", length=0.5, radius=0.0005, enabled=True,  color=(0.5,0,0.8))
#mesh2.add_vector_quantity("n2", -nt2, defined_on="faces", length=0.5, radius=0.0005, enabled=True,  color=(0,0.5,0))

# Visualize sphere radius as scalar quantity
mesh.add_scalar_quantity("radius sphere", nr, defined_on="faces", enabled=True, cmap="coolwarm")

# Visualize planarity as scalar quantity
mesh.add_scalar_quantity("planarity1", planarity1, defined_on="faces", enabled=True, cmap="coolwarm")
mesh.add_scalar_quantity("planarity2", planarity2, defined_on="faces", enabled=True, cmap="coolwarm")
mesh.add_scalar_quantity("Avg planarity", avg_planarity, defined_on="faces", enabled=True, cmap="coolwarm")
mesh.add_scalar_quantity("Validity", validity, defined_on="faces", enabled=True, cmap="jet")

mesh.add_vector_quantity("t1", t1, defined_on="faces", length=0.01, enabled=True,  color=(1,1,1))
mesh.add_vector_quantity("t2", t2, defined_on="faces", length=0.01, enabled=True,  color=(0,0,0))
#mesh.add_vector_quantity("Circum normal", -nt, defined_on="faces", length=4, enabled=True, vectortype="ambient", color=(0,0,0))
#mesh.add_vector_quantity("Circum normal1", nt, defined_on="faces", length=4, enabled=True, vectortype="ambient", color=(0,0,0))

ps.show()

In [ ]:
v = np.array([1,2,3,4,5,6])

3 * np.repeat(v, 3) + np.tile(range(3), len(v))

In [ ]:
## Extract variables
ne, nc, nr, th, phi = optimizer.uncurry_X("e", "sph_c", "sph_r", "th", "phi")

ne = ne.reshape((-1,3))
nc = nc.reshape((-1,3))

vv = v + ne
i, j, k = f[:,0], f[:,1], f[:,2]
vi, vj, vk = v[i], v[j], v[k]

vij = vj - vi 
vki = vk - vi

t1 = unit( np.cos(th)[:,None]*vij +  np.sin(th)[:,None]*vki)
t2 = unit(np.cos(th + phi)[:,None]*vij + np.sin(th + phi)[:,None]*vki)

tt1 = unit( np.cos(th)[:,None]*(vv[j] - vv[i]) +  np.sin(th)[:,None]*(vv[k] - vv[i]))
tt2 = unit(np.cos(th + phi)[:,None]*(vv[j] - vv[i]) + np.sin(th + phi)[:,None]*(vv[k] - vv[i]))

# Compute planarity
planarity1 = planarity_check(t1, tt1, ec)

planarity2 = planarity_check(t2, tt2, ec)

avg_planarity = (planarity1 + planarity2)/2
## Visualize
ps.init()
ps.remove_all_structures()

# Show boundary spheres
for id in range(len(boundary_faces)):
    i = boundary_faces[id]
    c = nc[i] 
    sphere = ps.register_point_cloud(f"sphere_c{i}", np.array([c]), enabled=True, color=(0,0,0), transparency=0.5)
    sphere.set_radius(nr[i], relative=False)



ps.register_point_cloud("cr", ct, enabled=True, radius=0.001, color=(0,0,0))
mesh = ps.register_surface_mesh("mesh", v, f)
mesh2 = ps.register_surface_mesh("mesh 2", vv, f)
mesh.add_vector_quantity("n", ne, length=1, enabled=True, vectortype="ambient", radius=0.0005, color=(0,0,0))


# Show sphere circumcircle axis
#mesh.add_vector_quantity(  "n",   nt, defined_on="faces", length=0.5, radius=0.0005, enabled=True,  color=(0.5,0,0.8))
#mesh2.add_vector_quantity("n2", -nt2, defined_on="faces", length=0.5, radius=0.0005, enabled=True,  color=(0,0.5,0))

# Visualize sphere radius as scalar quantity
mesh.add_scalar_quantity("radius sphere", nr, defined_on="faces", enabled=True, cmap="coolwarm")

# Visualize planarity as scalar quantity
mesh.add_scalar_quantity("planarity1", planarity1, defined_on="faces", enabled=True, cmap="coolwarm")
mesh.add_scalar_quantity("planarity2", planarity2, defined_on="faces", enabled=True, cmap="coolwarm")
mesh.add_scalar_quantity("Avg planarity", avg_planarity, defined_on="faces", enabled=True, cmap="coolwarm")
mesh.add_scalar_quantity("Validity", validity, defined_on="faces", enabled=True, cmap="jet")

mesh.add_vector_quantity("t1", t1, defined_on="faces", length=0.01, enabled=True,  color=(1,1,1))
mesh.add_vector_quantity("t2", t2, defined_on="faces", length=0.01, enabled=True,  color=(0,0,0))
#mesh.add_vector_quantity("Circum normal", -nt, defined_on="faces", length=4, enabled=True, vectortype="ambient", color=(0,0,0))
#mesh.add_vector_quantity("Circum normal1", nt, defined_on="faces", length=4, enabled=True, vectortype="ambient", color=(0,0,0))

ps.show()

In [ ]:
v = np.random.rand(4,3)
u = np.random.rand(4,3)

uv = vec_dot(u, v)
vv = vec_dot(v, v)

p = u - (uv/vv)[:,None]*v

vec_dot(p, v)



In [ ]:
3*np.arange(0, 3)+1

In [ ]:
import os 
import sys

# Add hananLab to path
#path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(os.getcwd()))))
path = os.path.dirname(os.getcwd())
sys.path.append(path)

import igl
import polyscope as ps
import numpy as np


from hanan.geometry.mesh import Mesh
from hanan.geometry.utils import *
from hanan.optimization.Sphericity import Sphericity
from hanan.optimization.Optimizer import Optimizer
from hanan.optimization.LineCong import LineCong
from hanan.optimization.LineCong_Fairness import LineCong_Fair
from hanan.optimization.Torsal import Torsal
from hanan.optimization.Torsal_fairness import Torsal_Fair


# Define paths
dir_path = os.getcwd()
data_path = dir_path+"/approximation/data/" # data path

# Load test mesh
#v, f = igl.read_triangle_mesh(os.path.join(data_path, "New_Tri_mesh.obj"))

# fix seed
np.random.seed(0)
v = np.random.rand(4,3)
f = np.array([[0,1,2], [0,2,3]])

n = igl.per_vertex_normals(v, f)

# Create mesh
mesh = Mesh()
mesh.make_mesh(v, f)

# Compute mesh properties
dual_top          = mesh.vertex_ring_faces_list()
inner_vertices    = mesh.inner_vertices()
vertex_adj        = mesh.vertex_adjacency_list()
boundary_faces    = mesh.boundary_faces()
boundary_vertices = mesh.boundary_vertices()
inner_edges       = mesh.inner_edges()

# Get vertex indices of each edge
ed_i, ed_j = mesh.edge_vertices()

ed_i = ed_i[inner_edges]
ed_j = ed_j[inner_edges]

# Get oposite vertex indices of each edge
ed_k, ed_l = mesh.edge_oposite_vertices()

ed_k = ed_k[inner_edges]
ed_l = ed_l[inner_edges]

print(f"ed_i: {ed_i}")
print(f"ed_j: {ed_j}")
print(f"ed_k: {ed_k}")
print(f"ed_l: {ed_l}")

# Fix direction
signs = np.sign(np.sum(n * ([0,0,-1]), axis=1))
n = n * signs[:, None]

# compute line congruence
e = 5 * n

# Compute second envelope
vv = v + e

# Compute indices of vertices of each face
i, j, k = f[:,0], f[:,1], f[:,2]


# Compute guess for sphere
ct, _, nt = circle_3pts(v[i], v[j], v[k])
ct2, _, nt2 = circle_3pts(vv[i], vv[j], vv[k])


for bf in boundary_faces:
    for bv in f[bf]:
        if bv in boundary_vertices:
            n[bv] = nt[bf]
            np.delete(boundary_vertices, np.where(boundary_vertices == bv))


vc  = np.sum(v[f], axis=1)/3
vvc = np.sum(vv[f], axis=1)/3


# Compute sphere center
signs = np.sign(np.sum(nt * ([0,0,-1]), axis=1))
nt = nt * signs[:, None]

sph_c = ct + 0.5*np.linalg.norm(ct2 - ct,axis=1)[:,None]*nt


# Compute sphere radius
sph_r = np.linalg.norm(sph_c - v[i], axis=1)

# Compute number of variables
nV = len(v)
nF = len(f)
nIE = len(inner_edges)


# Define variable indices
var_idx = {     "e"     : np.arange( 0            , 3*nV),  # Line congruence
                "sph_c" : np.arange( 3*nV         , 3*nV +  3*nF),  # Sphere centers
                "sph_r" : np.arange( 3*nV +  3*nF , 3*nV +  4*nF),  # Sphere radius
                "th"    : np.arange( 3*nV +  4*nF , 3*nV +  5*nF),  # theta  angle <t1, vji
                "phi"   : np.arange( 3*nV +  5*nF , 3*nV +  6*nF),  # phi  angel < t1, t2
                "nt1"   : np.arange( 3*nV +  6*nF , 3*nV +  9*nF),  # Normal torsal plane t1 
                "nt2"   : np.arange( 3*nV +  9*nF , 3*nV +  12*nF),  # Normal torsal plane t2
                "u"     : np.arange( 3*nV +  12*nF , 3*nV + 12*nF + 3*nIE)  # Normal torsal plane t2
        }



# Init X 
X = np.zeros(sum(len(arr) for arr in var_idx.values()))

print(len(X))
print(3*nV + 12*nF + 3*nIE)
print(var_idx["u"][3*i])

X[var_idx["e"]]      = e.flatten()
X[var_idx["sph_c"]]  = sph_c.flatten()
X[var_idx["sph_r"]]  = sph_r

t1, t2, a1, a2, b, validity = solve_torsal(v[i], v[j], v[k] , e[i], e[j], e[k])

tt1 = unit(a1[:,None]*(vv[j] - vv[i]) + b[:,None]*(vv[k] - vv[i]))
tt2 = unit(a2[:,None]*(vv[j] - vv[i]) + b[:,None]*(vv[k] - vv[i]))

ec = np.sum(e[f], axis=1)/3

# Init Sphericity
sphericity = Sphericity()
sphericity.initialize_constraint(X, var_idx, f, v)

# Init Line Congruence Fairnes
line_fair = LineCong_Fair()
line_fair.initialize_constraint(X, var_idx, vertex_adj, inner_vertices) 
line_fair.set_weigth(0.001)

# Init Line Cong
linecong = LineCong()
linecong.initialize_constraint(X, var_idx, len(v),  dual_top, inner_vertices)

# Init Torsal 
torsal = Torsal()
torsal.initialize_constraint(X, var_idx, v, f)

# Init Torsal 
torsal_fair = Torsal_Fair()
torsal_fair.initialize_constraint(X, var_idx, v, e, inner_edges, ed_i, ed_j, ed_k, ed_l)

#  Optimizer
optimizer = Optimizer()
optimizer.initialize_optimizer(X, var_idx, "LM", 0.5, 1)


it = 60
for _ in range(it):
    # optimizer.unitize_variable("nt1", 3)
    # optimizer.unitize_variable("nt2", 3)
    
    # optimizer.get_gradients(sphericity)
    # optimizer.get_gradients(linecong)
    # optimizer.get_gradients(torsal)
    # optimizer.get_gradients(line_fair)
    optimizer.get_gradients(torsal_fair)
    optimizer.optimize()




In [1]:
import igl
import polyscope as ps
import numpy as np

v, f=igl.read_triangle_mesh("/Users/cisneras/Darboux_Transformation_Data/DT1_tri.obj")

spheres = np.loadtxt("/Users/cisneras/Darboux_Transformation_Data/sph_tri.dat",  dtype=float, delimiter="\t")


ps.init()
ps.remove_all_structures()

for _ in range(10):
    i = np.random.randint(0, len(f))
    sph = spheres[i]
    ps.register_point_cloud(f"sphere_{i}", np.array([sph[0:3]]), enabled=True, color=(0,0,0), transparency=0.5)
    ps.get_point_cloud(f"sphere_{i}").set_radius(sph[3], relative=False)
ps.register_surface_mesh("mesh", v, f)
ps.show()



[polyscope] Backend: openGL3_glfw -- Loaded openGL version: 4.1 Metal - 88


In [1]:
import os 
import sys

path = os.path.dirname(os.getcwd())
sys.path.append(path)

import igl
import polyscope as ps
import numpy as np


from hanan.geometry.mesh import Mesh
from hanan.geometry.utils import *
from hanan.optimization.Sphericity import Sphericity
from hanan.optimization.Optimizer import Optimizer
from hanan.optimization.LineCong import LineCong
from hanan.optimization.LineCong_Fairness import LineCong_Fair
from hanan.optimization.Torsal import Torsal
from hanan.optimization.Torsal_fairness import Torsal_Fair

import igl
import polyscope as ps
import numpy as np

v, f=igl.read_triangle_mesh("/Users/cisneras/hanan/hananLab/TriMesh_start.obj")

mesh = Mesh()
mesh.make_mesh(v, f)

face_neighbors = mesh.face_face_adjacency_list()

file_export = open("/Users/cisneras/hanan/hananLab/TriMesh_face_neighbors.dat", "w")

# Export face neighbors to .dat file
for i in range(len(face_neighbors)):
    for j in range(len(face_neighbors[i])-1):
        file_export.write(f"{face_neighbors[i][j]}\t")
    file_export.write(f"{face_neighbors[i][-1]}\n")

file_export.close()

Mesh Data Structure: |V| = 247, |F| = 435, |E| = 681


  o TriMesh_start


In [2]:
import numpy as np
import igl 
import meshplot as mp
import polyscope as ps  
import os
import sys

path = os.path.dirname(os.getcwd())
sys.path.append(path)

from hanan.geometry.utils import initialize_Line_Congruence, unit
from hanan.geometry.mesh import Mesh

# Define the center and radius of the hexagon
radius = 2
offset = 1
center = np.array([0, 0, 0])


# Calculate the coordinates of the hexagon vertices
h_v = np.array([center + radius * np.array([np.cos(2 * np.pi * k / 6), np.sin(2 * np.pi * k / 6), offset + np.random.random()]) for k in range(6)])

center = center +  np.array([0, 0, np.mean(h_v[:,2])])

# Include the center as a vertex
h_v = np.vstack((center, h_v)) 

# Define the face list with triangle indices
h_f = np.vstack((np.array([[i, (i + 1)%7, 0] for i in range(1, 6)]), np.array([6,1,0])))

h_n = -igl.per_vertex_normals(h_v, h_f)

_, _, k1, k2 = igl.principal_curvature(h_v, h_f)


H = (0.5 + 0.002*np.random.rand(len(h_v)))*0.5

r = 1/H 


mesh = Mesh()
mesh.make_mesh(h_v, h_f)

dual_top = mesh.dual_top()

v_f_adj = mesh.vertex_face_adjacency_list()

e, mid, sph_c, sph_r = initialize_Line_Congruence(h_v, h_f, v_f_adj, h_n, H )


print(f"e: {e}")

ps.init()
ps.remove_all_structures()


for _ in range(10):
    i = np.random.randint(0, len(h_f))
    sphere = ps.register_point_cloud(f"sphere_{i}", np.array([sph_c[i]]), enabled=True, color=(0,0,0), transparency=0.5)
    sphere.set_radius(sph_r[i], relative=False)

hexmesh = ps.register_surface_mesh("hexagon", h_v, h_f)
mid_mesh = ps.register_surface_mesh("Mid", np.array(mid), h_f)
center_mesh = ps.register_surface_mesh("central mesh", sph_c, dual_top)
hexmesh. add_scalar_quantity("H", H, enabled=True, cmap="coolwarm")
hex2_mesh = ps.register_surface_mesh("hexagon 2", h_v + e, h_f, enabled=True)
hexmesh.add_vector_quantity("e", e, vectortype="ambient", enabled=True, color=(0,0,0))

ps.show()

Mesh Data Structure: |V| = 7, |F| = 6, |E| = 12
e: [[ 0.02158486  1.07152247 -7.55558012]
 [        nan         nan         nan]
 [        nan         nan         nan]
 [        nan         nan         nan]
 [        nan         nan         nan]
 [        nan         nan         nan]
 [        nan         nan         nan]]


In [19]:
test = np.array([[0.77775115,  0.58947903,  0.21821464],[ 0.74895543, -0.50886431,  0.42440885]])

print(np.mean(test, axis=1))
print(np.mean(test, axis=0))


[0.52848161 0.22149999]
[0.76335329 0.04030736 0.32131174]


In [1]:
import os 
import sys

# Add hananLab to path
#path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(os.getcwd()))))
path = os.path.dirname(os.getcwd())
sys.path.append(path)

import igl
import polyscope as ps
import numpy as np
import meshplot as mp


from hanan.geometry.mesh import Mesh
from hanan.geometry.utils import *
from hanan.optimization.Sphericity import Sphericity
from hanan.optimization.Optimizer import Optimizer
from hanan.optimization.LineCong import LineCong
from hanan.optimization.LineCong_Fairness import LineCong_Fair
from hanan.optimization.Torsal import Torsal
from hanan.optimization.Torsal_fairness import Torsal_Fair


# Define paths
dir_path = os.getcwd()
data_path = dir_path+"/approximation/data/" # data path

# Load test mesh
v, f = igl.read_triangle_mesh(os.path.join(data_path, "static.obj"))

v = normalize_vertices(v)



ps.init()
ps.remove_all_structures()

ps.register_surface_mesh("mesh", v, f)

ps.show()



[polyscope] Backend: openGL3_glfw -- Loaded openGL version: 4.1 Metal - 88


: 

In [2]:
import os 
import sys

# Add hananLab to path
#path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(os.getcwd()))))
path = os.path.dirname(os.getcwd())
sys.path.append(path)

import igl
import polyscope as ps
import numpy as np
import meshplot as mp


from hanan.geometry.mesh import Mesh
from hanan.geometry.utils import *
from hanan.optimization.Sphericity import Sphericity
from hanan.optimization.Optimizer import Optimizer
from hanan.optimization.LineCong import LineCong
from hanan.optimization.LineCong_Fairness import LineCong_Fair
from hanan.optimization.Torsal import Torsal
from hanan.optimization.Torsal_fairness import Torsal_Fair


# Load test mesh
v, f = igl.read_triangle_mesh("/Users/cisneras/Downloads/mire.obj")
#v = normalize_vertices(v)

ps.init()
ps.remove_all_structures()

ps.register_surface_mesh("mesh", v, f)

ps.show()


IOError: /Users/cisneras/Downloads/mire.obj could not be opened...


ValueError: File '/Users/cisneras/Downloads/mire.obj' not found.

In [6]:
import os 
import sys

# Add hananLab to path
#path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(os.getcwd()))))
path = os.path.dirname(os.getcwd())
sys.path.append(path)

import igl
import polyscope as ps
import numpy as np
import meshplot as mp


from hanan.geometry.mesh import Mesh
from hanan.geometry.utils import *
from hanan.optimization.Sphericity import Sphericity
from hanan.optimization.Optimizer import Optimizer
from hanan.optimization.LineCong import LineCong
from hanan.optimization.LineCong_Fairness import LineCong_Fair
from hanan.optimization.Torsal import Torsal
from hanan.optimization.Torsal_fairness import Torsal_Fair


# Compute the normal vector of the polygonal face
normal_vector = np.mean(np.cross(edges[ei], edges[ej]), axis=0)

n = -igl.per_vertex_normals(v, f)

_, _, k1, k2 = igl.principal_curvature(v, f)


H = 0.5*(k1 + k2)

r = 1/H 

mesh = Mesh()
mesh.make_mesh(v, f)

v_f_adj = mesh.vertex_face_adjacency_list()

#cc, _, _ = circle_3pts(v[f[:,0]], v[f[:,1]], v[f[:,2]])

e = 2*n

vv = v+e

sph_c = sphere_initialization(v, f, e)

sph_r = np.linalg.norm(sph_c - v[f[:,0]], axis=1)

vi, vj, vk = v[f[:,0]], v[f[:,1]], v[f[:,2]]
vvi, vvj, vvk = vv[f[:,0]], vv[f[:,1]], vv[f[:,2]]

# Get circum circles for both envelopes
p1,  cr,  v1 = circle_3pts(vi, vj, vk)
p2, cr2,  v2 = circle_3pts(vvi, vvj, vvk)


ps.init()
ps.remove_all_structures()



for _ in range(10):
    i = np.random.randint(0, len(f))
    print(f"i: {i}")
    sphere = ps.register_point_cloud(f"sphere_{i}", np.array([sph_c[i]]), enabled=True, color=(0,0,0), transparency=0.5)
    sphere.set_radius(sph_r[i], relative=False)
    print(f"Radius of sphere {i}: {sph_r[i]}")
    


mesh = ps.register_surface_mesh("Mesh", v, f)
mesh2 = ps.register_surface_mesh("Mesh2", vv, f)

cc1 = ps.register_point_cloud("Circum Centers M1", p1)
cc2 = ps.register_point_cloud("Circum Centers M2", p2)

cc1.add_vector_quantity("axis 1", v1)
cc2.add_vector_quantity("axis 2", v2)

ps.register_point_cloud("Centers", sph_c)


mesh.add_vector_quantity("e", e,  vectortype="ambient", radius = 0.001, enabled=True, color=(0,0,0))
#hex2_mesh = ps.register_surface_mesh("hexagon 2", v + e, f)
#hexmesh.add_vector_quantity("e", e, vectortype="ambient", enabled=True, color=(0,0,0))

ps.show()



Mesh Data Structure: |V| = 309, |F| = 576, |E| = 884
[ 7.08631323e-03  1.08310143e-02  1.82484836e-03  1.46224046e-02
  3.57451594e-03  1.08804962e-02  2.60125870e-03  6.29385384e-04
  2.48112671e-03  9.76019857e-03  2.50653518e-03  1.33732418e-02
  2.55518970e-03  1.33182685e-02  3.89826765e-02  2.39207979e-03
  3.46369592e-03  5.76083690e-03  1.13533795e-02  3.77766043e-03
  4.49166530e-03  7.18383956e-03  6.58898856e-03  7.21338650e-03
  3.14180396e-02  8.56205104e-03  1.50993036e-02  3.19229615e-02
  3.23794214e-02  8.89462663e-03  9.38136306e-03  2.94085220e-02
  2.58494192e-02  6.28241316e-02  4.61400978e-02  6.29227245e-03
  1.88533569e-02  2.35003053e-02  1.26435267e-02  9.04090970e-03
  8.42626449e-03  1.71696464e-02  1.06393184e-02  1.38388129e-02
  3.02557213e-02  1.11578469e-02  2.84017043e-02  3.72250601e-02
  7.90215290e-03  7.90812114e-03  3.58159229e-04  1.62948481e-02
  5.90862751e-03  9.42790765e-03  6.87396267e-03  6.09868863e-03
  7.81075484e-03  8.24271754e-03  1.4

In [2]:
import numpy as np

v = np.array([[0,0,0], [1,0,0], [1,1,0], [0,1,0], [0.5,0.5,1]])

size = np.array([1,2,1])

size*v

array([[0. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 2. , 0. ],
       [0. , 2. , 0. ],
       [0.5, 1. , 1. ]])

In [3]:
import numpy as np

indices = np.arange(0, 10)

# Add 12 more indices to the array in order
indices = np.hstack((indices, np.arange(10, 22)))


In [6]:
# create a 3x3 matrix
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
# Different one 
b = np.array([[1,2,3],[4,1,6],[7,2,9]])

stacked = []
stacked.append(a)
stacked.append(b)

np.vstack(stacked)



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 1, 6],
       [7, 2, 9]])

In [4]:
import timeit
import numpy as np

# Define setup code
setup_code = """
import numpy as np
i = []
"""

# Define extend and append approach
extend_code = """
i.extend(np.random.randint(1, 100, size=4).tolist())
i.extend(np.random.randint(1, 100, size=4).tolist())
"""

append_code = """
i.append(np.random.randint(1, 100, size=4))
i.append(np.random.randint(1, 100, size=4))
flatten(i)
"""

# Define flatten function
flatten_function = """
def flatten(lst):
    return [item for sublist in lst for item in sublist]
"""

# Define flattening the list approach
flatten_extend_code = """
flattened_i = flatten(i)
"""

flatten_append_code = """
flattened_i = flatten(i)
"""

# Measure execution time for extend approach
time_extend = timeit.timeit(extend_code, setup=setup_code , number=10000)

# Measure execution time for append approach
time_append = timeit.timeit(append_code, setup=setup_code + flatten_function, number=10000)


print("Execution time for extend():", time_extend)
print("Execution time for append():", time_append)

Execution time for extend(): 0.14008483299994623
Execution time for append(): 64.85568508300003


In [8]:
import numpy as np

nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
x_g, y_g = np.meshgrid(x, y)

pts = list(zip(x_g.ravel(), y_g.ravel()))
print(pts)


[(0.0, 0.0), (0.5, 0.0), (1.0, 0.0), (0.0, 1.0), (0.5, 1.0), (1.0, 1.0)]


In [44]:
import numpy as np

def custom_operation(A, B):
    # A is m x n, B is p x q
    # Output should be (m*p) x (n*q)
    
    # Step 1: Multiply each element of A with B using broadcasting
    # Reshape A to (m, 1, n, 1) and B to (1, p, 1, q) for compatible broadcasting
    result = A[:, np.newaxis, :, np.newaxis] * B[np.newaxis, :, np.newaxis, :]
    
    # Step 2: Reshape and reorder the result to get the desired output shape
    # The resulting shape should be (m*p, n*q)
    m, p, n, q = result.shape
    print(m, p, n, q)
    result = result.transpose(0, 2, 1, 3).reshape(m*p, n*q)
    
    return result

# Example usage
A = np.array([[1, 2], [10, 20]])  # 2x3 matrix

B = np.array([[5, 6, 7], [8, 9, 10]])  # 2x4 matrix

R = np.kron(A,B).repeat(3, axis=0)
print(R)


[[  5   6   7  10  12  14]
 [  5   6   7  10  12  14]
 [  5   6   7  10  12  14]
 [  8   9  10  16  18  20]
 [  8   9  10  16  18  20]
 [  8   9  10  16  18  20]
 [ 50  60  70 100 120 140]
 [ 50  60  70 100 120 140]
 [ 50  60  70 100 120 140]
 [ 80  90 100 160 180 200]
 [ 80  90 100 160 180 200]
 [ 80  90 100 160 180 200]]


In [66]:
import numpy as np

def create_efficient_block_matrix(n, m):
    """
    Create a block matrix of dimension 3n x 3m filled with n x m identity matrices of 3x3,
    using a more efficient method.

    Parameters:
    - n: int, number of 3x3 identity matrices vertically.
    - m: int, number of 3x3 identity matrices horizontally.

    Returns:
    - block_matrix: ndarray, block matrix of dimension 3n x 3m.
    """
    # Create an n x m matrix of ones
    ones_matrix = np.ones((n, m))

    # Create a 3x3 identity matrix
    identity_block = np.eye(3)

    # Use Kronecker product to create the block matrix
    block_matrix = np.kron(ones_matrix, identity_block)

    return block_matrix

# Example usage
n, m = 4, 3  # Define the size of the block matrix

Nu = np.array([1 ,  2,  3,4])
Nv = np.array([10, 20, 30])
block_matrix = create_efficient_block_matrix(n, m)
#print(block_matrix)

print("kron: \n",np.kron(Nu, Nv))
print("nPM: \n", np.outer(Nu, Nv))




kron: 
 [ 10  20  30  20  40  60  30  60  90  40  80 120]
nPM: 
 [[ 10  20  30]
 [ 20  40  60]
 [ 30  60  90]
 [ 40  80 120]]


In [9]:
import numpy as np
u_vals = np.array([1, 2, 3])
v_vals = np.array([10, 20, 30])

vals = np.outer(u_vals, v_vals)

u_g, v_g = np.meshgrid(u_vals, v_vals, indexing='ij')   
print("u_grid:", u_g.flatten())
print("v_grid:", v_g.flatten())
print("vals:", vals.flatten())  
print("vals:\n", vals)

u_grid: [1 1 1 2 2 2 3 3 3]
v_grid: [10 20 30 10 20 30 10 20 30]
vals: [10 20 30 20 40 60 30 60 90]
vals:
 [[10 20 30]
 [20 40 60]
 [30 60 90]]


In [16]:
import numpy as np

A = np.array([[[1,2,3],[1,2,3]],[[10,20,30],[11,12,13]]])
B = np.array([[[5,6,7],[0,1,0]],[[8,9,10],[8,9,10]]])

print(np.cross(A, B, axis=2))

print(np.cross(A[0,0], B[0,1]))



[[[ -4   8  -4]
  [ -3   0   1]]

 [[-70 140 -70]
  [  3  -6   3]]]
[-3  0  1]


In [10]:
import numpy as np
import os 
import sys

path = os.path.dirname(os.getcwd())
sys.path.append(path)

import igl
import polyscope as ps
import numpy as np


from hanan.geometry.mesh import Mesh
from hanan.geometry.utils import *

v = np.random.rand(330, 3)
m = np.random.rand(3)
n = np.random.rand(330, 3)


value =  (-vec_dot(v - m, n) * (-2 * vec_dot(v - m, v - m) ))[:, None] * n + 2 * (vec_dot(v-m, n) / (vec_dot(v - m, v - m) ** 2))[:,None] * (v-m)
value2 =  - (vec_dot(n, v) * vec_dot(n, v)) / vec_dot(v, v)

print(value)

[[ 4.77309304e+00  7.40998295e+00  5.31323782e+00]
 [ 1.14158108e+00 -1.56389800e+00  5.36292677e+00]
 [-5.20554351e-03  2.96914271e+00 -3.49244633e-02]
 [ 5.45265790e+00 -1.29194709e+00  9.78597777e-01]
 [ 7.53579513e+00 -7.76575061e-02 -2.51064013e+00]
 [ 3.38305852e-03 -5.09172377e-03  3.41935760e-03]
 [-5.96829807e-01  1.56687642e-01 -2.68958573e-01]
 [ 1.83163970e-01  3.01878575e-01 -2.61507994e-01]
 [ 2.42766694e+01 -5.55213367e+00  1.54667077e+01]
 [ 1.73141856e+00  1.12905204e+00  2.65452078e-01]
 [-4.96261894e-01  4.64582235e-01 -7.83831080e-01]
 [ 1.17383956e+00  3.12966870e-01 -5.67601063e-01]
 [ 3.19204215e+00 -4.56262242e-01  2.53716560e+00]
 [ 6.00796397e-02 -6.65235017e-02 -1.01755646e-01]
 [-7.62353816e-01 -6.79870483e-01  1.69831560e+00]
 [ 4.03866456e+00 -4.07974427e+00 -3.99210008e+00]
 [-9.50315906e-01  7.62118859e-01  7.20908136e-02]
 [-4.07998713e-02  5.97016707e-02 -4.87296721e-02]
 [-5.75493388e-01  1.35566431e+00 -1.60065653e-01]
 [ 1.16352391e+00 -4.68755084e-

In [8]:
import numpy as np
u = 5
v = 5
r  = np.random.rand(u,v)
ru = np.random.rand(u,v)
rv = np.random.rand(u,v)
n  = np.random.rand(u,v,3)
nu = np.random.rand(u,v,3)
nv = np.random.rand(u,v,3)

print("axis 2: ",np.cross(ru[:,:,None]*n, rv[:,:,None]*n, axis=2)[0],"\n no axis: ",np.cross(ru[:,:,None]*n, rv[:,:,None]*n)[0])





axis 2:  [[-1.38777878e-17  2.77555756e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.38777878e-17 -1.38777878e-17  0.00000000e+00]
 [ 8.67361738e-19 -1.73472348e-18  0.00000000e+00]
 [ 1.38777878e-17 -6.93889390e-18  0.00000000e+00]] 
 no axis:  [[-1.38777878e-17  2.77555756e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.38777878e-17 -1.38777878e-17  0.00000000e+00]
 [ 8.67361738e-19 -1.73472348e-18  0.00000000e+00]
 [ 1.38777878e-17 -6.93889390e-18  0.00000000e+00]]


In [7]:
import numpy as np

# Initial array
initial_array_np = np.array([1, 9, 0, 10])

# Vectorized transformation using numpy
def transform_array_numpy(arr, n=5):
  # Multiply elements by 3
    multiplied = arr * n
    # Create a sequence for each element and reshape for concatenation
    for i in range(1, n):
        multiplied = np.vstack([multiplied, arr * n + i])
    
    # Flatten the array to match the desired output format
    transformed = multiplied.flatten('F')
    return transformed

# Apply the numpy transformation
transformed_array_numpy = transform_array_numpy(initial_array_np)
print(transformed_array_numpy)

[ 5  6  7  8  9 45 46 47 48 49  0  1  2  3  4 50 51 52 53 54]


In [14]:
import numpy as np
import pymeshlab
import polyscope as ps

# Assuming V and F are your vertices and faces arrays
# For demonstration, let's create some dummy data
# V: 3D positions of vertices (N x 3 numpy array)
# F: Indices of vertices that compose each face (M x 3 numpy array for triangles)
V = np.array([[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]], dtype=np.float32)
F = np.array([[0, 1, 2], [0, 1, 3], [0, 2, 3], [1, 2, 3]], dtype=np.int32)

# Create a new MeshSet instance
m = pymeshlab.Mesh(V, F)

# create a new MeshSet
ms = pymeshlab.MeshSet()

# add the mesh to the MeshSet
ms.add_mesh(m, "Mesh")


# Perform isotropic remeshing
ms.meshing_isotropic_explicit_remeshing(targetlen=pymeshlab.PercentageValue(1))

# You can extract the remeshed mesh's vertices and faces if needed
remeshed_mesh = ms.current_mesh()
remeshed_V = remeshed_mesh.vertex_matrix()
remeshed_F = remeshed_mesh.face_matrix()

# If you want to save the remeshed mesh to a file
ps.init()

ps.remove_all_structures()

ps.register_surface_mesh("mesh", V, F)
ps.register_surface_mesh("remeshed", remeshed_V, remeshed_F)

ps.show()


In [5]:
import numpy as np
from scipy import sparse
import time
# Compare coo with csc matrix multiplication

def create_sparse_matrix(n_rows, n_cols):
    """Creates a sparse matrix of the given shape with random data."""
    rng = np.random.default_rng()
    r = rng.integers(0, n_rows, size=int(n_rows*n_cols*0.5))  # 10% sparsity
    c = rng.integers(0, n_cols, size=int(n_rows*n_cols*0.5))
    data = rng.random(r.shape[0])
    return sparse.csc_matrix((data, (r, c)), shape=(n_rows, n_cols))

def stack_matrices(matrices):
    """Stacks sparse matrices vertically."""
    return sparse.vstack(matrices)

def compute_directly(J):
    """Computes H = J.T * J directly."""
    #return J.T.dot(J)
    return J.T.dot(J)

def compute_incrementally(matrices):
    """Computes H incrementally as sum of H_i for each J_i."""
    H_sum = sum(J_i.T.dot(J_i) for J_i in matrices)
    return H_sum

# Example usage
n_matrices = 10  # Number of J_i matrices
n_rows, n_cols = 10000, 600  # Size of each J_i matrix

# Generate sparse matrices J_i
matrices = [create_sparse_matrix(n_rows, n_cols) for _ in range(n_matrices)]

# Stack matrices to form J
J = stack_matrices(matrices)

# Time the direct computation
start_time = time.time()
H_direct = compute_directly(J)
direct_time = time.time() - start_time

# Time the incremental computation
start_time = time.time()
H_incremental = compute_incrementally(matrices)
incremental_time = time.time() - start_time

print(f"Direct computation took: {direct_time:.4f} seconds.")
print(f"Incremental computation took: {incremental_time:.4f} seconds.")


Direct computation took: 9.5567 seconds.
Incremental computation took: 7.5166 seconds.


In [3]:
import numpy as np
from scipy import sparse
import time
# Compare coo with csc matrix multiplication

def create_sparse_matrix(n_rows, n_cols):
    """Creates a sparse matrix of the given shape with random data."""
    rng = np.random.default_rng()
    r = rng.integers(0, n_rows, size=int(n_rows*n_cols*0.5))  # 10% sparsity
    c = rng.integers(0, n_cols, size=int(n_rows*n_cols*0.5))
    data = rng.random(r.shape[0])
    return sparse.coo_matrix((data, (r, c)), shape=(n_rows, n_cols))

def stack_matrices(matrices):
    """Stacks sparse matrices vertically."""
    return sparse.vstack(matrices)

def compute_directly(J):
    """Computes H = J.T * J directly."""
    #return J.T.dot(J)
    return J.T.dot(J)

def compute_incrementally(matrices):
    """Computes H incrementally as sum of H_i for each J_i."""
    H_sum = sum(J_i.T.dot(J_i) for J_i in matrices)
    return H_sum

# Example usage
n_matrices = 10  # Number of J_i matrices
n_rows, n_cols = 10000, 600  # Size of each J_i matrix

# Generate sparse matrices J_i
matrices = [create_sparse_matrix(n_rows, n_cols) for _ in range(n_matrices)]

# Stack matrices to form J
J = stack_matrices(matrices)

# Time the direct computation
start_time = time.time()
H_direct = compute_directly(J)
direct_time = time.time() - start_time

# Time the incremental computation
start_time = time.time()
H_incremental = compute_incrementally(matrices)
incremental_time = time.time() - start_time

print(f"Direct computation took: {direct_time:.4f} seconds.")
print(f"Incremental computation took: {incremental_time:.4f} seconds.")


Direct computation took: 13.6175 seconds.
Incremental computation took: 11.6002 seconds.


In [23]:
import time
import numpy as np
import random

# FILEPATH: /home/anthony/Hanan Lab/hananLab/hanan/testNotebook.ipynb
# I want to check if starting a list with a given size and then filling it with a for loop is faster than a list comprehension

# Define the number of times to run the code
num_runs = 10

# Initialize the total execution time variables
total_for_loop_time = 0
total_comprehension_time = 0

for _ in range(num_runs):
    # Start a list with a given size and fill it with a for loop
    start_time = time.time()
    size = 1000000
    list_for_loop = np.zeros(size)
    for i in range(size):
        list_for_loop[i] = random.randint(0, 100)
    for_loop_time = time.time() - start_time
    total_for_loop_time += for_loop_time

    # Use a list comprehension to create a list
    start_time = time.time()
    list_comprehension = [random.randint(0,100) for i in range(size)]
    comprehension_time = time.time() - start_time
    total_comprehension_time += comprehension_time

# Calculate the average execution time
average_for_loop_time = total_for_loop_time / num_runs
average_comprehension_time = total_comprehension_time / num_runs

print("Average execution time for the for loop approach:", average_for_loop_time)
print("Average execution time for the list comprehension approach:", average_comprehension_time)


Average execution time for the for loop approach: 1.378120756149292
Average execution time for the list comprehension approach: 1.0601283311843872


In [2]:
import numpy as np
import polyscope as ps
from scipy.spatial import KDTree


def distance_point_to_triangle(p, v0, v1, v2):
    """
    Compute the minimum distance between points p and a triangle defined by vertices v0, v1, and v2.
    """

    # Compute vectors
    v0v1 = v1 - v0
    v0v2 = v2 - v0
    p_v0 = p - v0

    # Compute dot products
    dot00 = np.sum(v0v1*v0v1, axis=1)
    dot01 = np.sum(v0v1*v0v2, axis=1)
    dot02 = np.sum(v0v1*p_v0, axis=1)
    dot11 = np.sum(v0v2*v0v2, axis=1)
    dot12 = np.sum(v0v2*p_v0, axis=1)

    

    # Compute barycentric coordinates
    inv_denom = 1 / (dot00 * dot11 - dot01 * dot01)
    u = (dot11 * dot02 - dot01 * dot12) * inv_denom
    v = (dot00 * dot12 - dot01 * dot02) * inv_denom

    # Clamp barycentric coordinates to avoid points outside the triangle
    u = np.clip(u, 0, 1)
    v = np.clip(v, 0, 1)

    # Compute closest points on the triangles
    closest_points = v0 + u[:, None] * v0v1 + v[:, None] * v0v2

    return closest_points, np.hstack((1-u-v, u, v))

def closest_point_on_mesh(mesh_vertices, mesh_triangles, query_points):
    """
    Compute the closest points on a triangular mesh to multiple query points using KDTree for efficiency.
    """

    vc = np.sum(mesh_vertices[mesh_triangles], axis=1) / 3

    tree = KDTree(vc)

    # Find nearest triangles
    dists, nearest_triangle_idxs = tree.query(query_points)

    # Get the faces that contain the nearest vertex idx
    # Search in wich face is contained that index

    # Get vertices of the nearest triangles
    nearest_triangles = mesh_triangles[nearest_triangle_idxs]

    print(nearest_triangles)

    # Get vertices of the nearest triangles
    v0 = mesh_vertices[nearest_triangles[:, 0]]
    v1 = mesh_vertices[nearest_triangles[:, 1]]
    v2 = mesh_vertices[nearest_triangles[:, 2]]

    # Compute closest points on the nearest triangles
    closest_points_on_triangles, bar_coord  = distance_point_to_triangle(query_points, v0, v1, v2)

    return closest_points_on_triangles, bar_coord

# Define mesh vertices and triangles (indices)
mesh_vertices = np.array([[0, 0, 0], [1, 0, 0], [0, 1, 0], [1, 1, 0]])
mesh_triangles = np.array([[0, 1, 2], [1, 2, 3]])

# Define query points
query_points = np.random.rand(10, 3)

# Compute closest points on mesh
closest_points, bar = closest_point_on_mesh(mesh_vertices, mesh_triangles, query_points)
    

ps.init()
ps.remove_all_structures()
ps.register_surface_mesh("mesh", mesh_vertices, mesh_triangles)
ps.register_point_cloud("query_point", np.array(query_points))
ps.register_point_cloud("closest_point", np.array(closest_points), color=(1.0, 0.0, 0.0))

ps.show()


query_points:  [[0.78415541 0.95032658 0.84838628]
 [0.59223497 0.94341499 0.96072537]
 [0.37438637 0.64740843 0.56155409]
 [0.78127915 0.95751255 0.59232459]
 [0.48993518 0.50712141 0.32675302]
 [0.06702471 0.59542497 0.01959709]
 [0.31344624 0.54801869 0.56756512]
 [0.30738658 0.63385392 0.98084917]
 [0.56008294 0.49419555 0.64925519]
 [0.52913137 0.77826612 0.52235826]]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [1 2 3]
 [1 2 3]]
inside
size v0:  (10, 3)
size v1:  (10, 3)
size v2:  (10, 3)
size p:  (10, 3)
