In [2]:
import numpy as np

## Determinant

In [ ]:
# Generate 5 random points in 3D
v1 = np.random.rand(5,3)
v2 = np.random.rand(5,3)
v3 = np.random.rand(5,3)

# Compute the determinant of the matrix formed by the vectors (v1, v2, v3) for each row
# The determinant is zero if the vectors are coplanar
cross = np.cross(v2, v3)


dets = np.sum(v1 * cross, axis=1)
print(f"Full Determiant : {dets}")
print(f"Det 0 : {np.linalg.det(np.array([v2[0], v3[0], v1[0]]))}")
print(f"Det 1 : {np.linalg.det(np.array([v2[1], v3[1], v1[1]]))}")
print(f"Det 2 : {np.linalg.det(np.array([v2[2], v3[2], v1[2]]))}")

## $v_{ij} \cdot (v_{ik} \times \partial e_c)*det2$

In [91]:
import numpy as np
import time

# Define the size of the matrices and vectors
n = 800  # Large number of rows
m = 3  # Number of columns
T = 200  # Number of repetitions

# Initialize variables to store total elapsed times
total_time_1 = 0
total_time_2 = 0


for t in range(T):
    # Generate random matrices and vectors
    eik = np.random.rand(n, m)
    derx = np.zeros((n, m))
    derx[:, 0] = 1
    nc = np.random.rand(n)

    print("init eik: \n", eik[:5])

    # Benchmark the first approach
    start_time = time.time()
    eikXdec_x_1 = np.cross(eik, derx) / nc[:, None]
    elapsed_time_1 = time.time() - start_time

    # Benchmark the second approach
    start_time = time.time()
    eikXdec_x_2 = eik[:, [0, 2, 1]] / nc[:, None]
    eikXdec_x_2[:, 0] = 0
    eikXdec_x_2[:, 1] *= -1  
    eikXdec_x_2 *= -1
    elapsed_time_2 = time.time() - start_time

    total_time_1 += elapsed_time_1
    total_time_2 += elapsed_time_2

    print("final eik: \n", eik[:5])
    print("*-----------------------------*")

    # asssert same
    assert(np.allclose(eikXdec_x_1, eikXdec_x_2))
    
total_time_1 /= T
total_time_2 /= T

# Print the elapsed times
print("Elapsed time for approach 1:", total_time_1, "seconds")
print("Elapsed time for approach 2:", total_time_2, "seconds")

init eik: 
 [[0.071056   0.82250158 0.83724218]
 [0.96970236 0.01156335 0.14151112]
 [0.33514132 0.87899737 0.51857544]
 [0.66994895 0.8476192  0.37996551]
 [0.5785526  0.32584775 0.50234261]]
final eik: 
 [[0.071056   0.82250158 0.83724218]
 [0.96970236 0.01156335 0.14151112]
 [0.33514132 0.87899737 0.51857544]
 [0.66994895 0.8476192  0.37996551]
 [0.5785526  0.32584775 0.50234261]]
*-----------------------------*
init eik: 
 [[0.14714703 0.50197858 0.67861647]
 [0.00734737 0.50162437 0.10875393]
 [0.16964042 0.50811756 0.78549256]
 [0.98218977 0.91305254 0.80413966]
 [0.71002047 0.14289083 0.36347319]]
final eik: 
 [[0.14714703 0.50197858 0.67861647]
 [0.00734737 0.50162437 0.10875393]
 [0.16964042 0.50811756 0.78549256]
 [0.98218977 0.91305254 0.80413966]
 [0.71002047 0.14289083 0.36347319]]
*-----------------------------*
init eik: 
 [[0.99364724 0.86284973 0.26296779]
 [0.05114542 0.46768408 0.69828489]
 [0.09084513 0.01116581 0.51709813]
 [0.50983806 0.84392752 0.39917546]
 [0.09

In [93]:
# 5 Random points
v1 = np.random.rand(5,3)
# 3 random faces indices
f1 = np.random.randint(0, 5, 3)

np.sum(v1[f1], axis=1)

array([1.64612126, 1.00475331, 1.11472158])

In [10]:
import numpy as np

n= 5
m= 6
J = np.zeros((n,m))
v = np.ones(3)
J[2:n, 3: 6] = v * np.eye(3)
print(J)

J[:3, 0:3] = np.diag(v)
print(J)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [37]:
import numpy as np
import time

n= 8
m= 8

J = np.repeat([0,1,2,3,4,5,6,7,8], 9).reshape((9,9)).T
i = 3*np.array([1, 2, 0, 1, 2, 0, 1, 2])
v = np.array([10, 20, 30, 10, 40, 50, 60, 2])
J[range(m), i] = v
print(J)

[[ 0  1  2 10  4  5  6  7  8]
 [ 0  1  2  3  4  5 20  7  8]
 [30  1  2  3  4  5  6  7  8]
 [ 0  1  2 10  4  5  6  7  8]
 [ 0  1  2  3  4  5 40  7  8]
 [50  1  2  3  4  5  6  7  8]
 [ 0  1  2 60  4  5  6  7  8]
 [ 0  1  2  3  4  5  2  7  8]
 [ 0  1  2  3  4  5  6  7  8]]


In [31]:
def cross_id(v, coord, type=0):
    """ Function tha retunr the cross product with coordinate vectors like [1, 0, 0], [0, 1, 0], [0, 0, 1]
        type 0
        V x [1,0,0]
        type 1
        [1,0,0] x V

    """

    if coord=='x':
        cross = v[:, [0, 2, 1]] 
        cross[:, 0] = 0
        cross[:, 2] *= -1 
    elif coord=='y':
        cross = v[:, [2, 1, 0]]
        cross[:, 0] *= -1
        cross[:, 1] = 0
    elif coord=='z':
        cross = v[:, [1, 0, 2]]
        cross[:, 1] *= -1
        cross[:, 2] = 0
    
    if type==1:
        cross *= -1

    return cross

In [45]:
v = np.random.rand(1000000, 3)

# Test time
id_time = 0
cross_time = 0
for i in range(500):
    s = time.time()
    id_c =  cross_id(v/3, 'x', 1)
    id_time += time.time() - s

    s = time.time()
    cr = np.cross(np.array([1, 0, 0]),v/3)
    cross_time += time.time() - s

    assert(np.allclose(id_c, cr))

print("average id_time: ", id_time/100)

print("average cross_time: ", cross_time/100)


average id_time:  0.01732025623321533
average cross_time:  0.01775730848312378


In [3]:
# Compute the edge vectors per each face
n = 4
vj = np.array([[1, 1,1], [2, 2,2], [3, 3,3], [4, 4,4]])
vi = np.array([[0, 1,0], [0, 0,0], [0, 0,0], [0, 0,0]])
vk = np.array([[10, 10, 10], [20, 20,20], [30, 30,30], [40, 40,40]])
fvij = np.empty((n, 2, 3), dtype=float)

# Compute the edge vectors per each face
fvij[:,0] = vj - vi
fvij[:,1] = vk - vi
print(fvij[:,0])

[[1. 0. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [4]:
np.sum( np.array([1,0,1])*vj, axis=1)

array([2, 4, 6, 8])

In [12]:
import numpy as np
face = np.array([0,3,5,1])
n = 6
m = 10
nli = 3
ei = np.array([[1,0,0],[0,1,0],[0,0,1]])
f = 1
ni = np.array([[1,2,3],[10,11,12],[4,5,6],[3,5,7]])
norms = np.array([[1,2,3,4],[5,6,7,8]])
J = np.zeros((n,m))

i = 1


J[range(i,i + len(face)), nli + face] = -np.sum( ei[f]*ni, axis=1)/norms[0, None]

print(J,-np.sum( ei[f]*ni, axis=1)/norms[0, None])

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.         -2.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
  -5.5         0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.         -1.66666667  0.        ]
 [ 0.          0.          0.          0.         -1.25        0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]] [[-2.         -5.5        -1.66666667 -1.25      ]]


In [23]:
import time 
import numpy as np

n = 1000
m = 1000
J = np.zeros((n,m))

a = 20
b = a*3
nt = np.random.randint(0, n, a)
v  = np.arange(0, b)
v1 = np.arange(0, b).reshape((20, 3))


tm  = 0
tm1 = 0
for i in range(1000):
    vals = np.random.rand(20,3)
    
    
    tic = time.time()
    J [nt.repeat(3), v] = vals.flatten()
    tm += time.time() - tic

    tic = time.time()
    J[nt, v1[:,0]] = vals[:,0]
    J[nt, v1[:,1]] = vals[:,1]
    J[nt, v1[:,2]] = vals[:,2]
    tm1 += time.time() - tic


tm /= 1000
tm1 /= 1000
print("tm: ", tm)
print("tm1: ", tm1)


tm:  1.310563087463379e-05
tm1:  1.9193410873413086e-05


In [32]:
# Test construction of sparse matrix

# 1) Create a normal matrix J and then convert it to csc_matrix


import numpy as np
import time
from scipy.sparse import csc_matrix, coo_matrix
# Measure memory usage
import psutil


n = 1000
m = 2000

time_normal = 0
time_coo = 0
time_csc = 0
time_hess_coo = 0
time_hess_csc = 0

for _ in range(200):

    
    # Random columns
    cols = np.random.randint(0, m, 200)
    # Random rows
    rows = np.random.randint(0, n, 200)

    # Random values
    vals = np.random.rand(200)


    # Fill the matrix normal
    # Take time and memory usage
    tic = time.time()
    
    J = np.zeros((n,m))
    J[rows, cols] = vals
    J_sparse = csc_matrix(J)
    
    toc = time.time()

    
    time_normal += toc - tic


    # Fill the matrix csc
    tic = time.time()
    J_sparse_csc = csc_matrix((vals, (rows, cols)), shape=(n, m))
    toc = time.time()

    time_csc += toc - tic

    tic = time.time()
    h = (J_sparse_csc.T * J_sparse_csc).tocsr()
    toc = time.time()

    time_hess_csc = toc - tic

    # Fill matrix coo
    tic = time.time()
    J_sparse_coo = coo_matrix((vals, (rows, cols)), shape=(n, m))
    toc = time.time()

    time_coo += toc - tic

    tic = time.time()
    h = (J_sparse_coo.T * J_sparse_coo).tocsr()
    toc = time.time()

    time_hess_coo = toc - tic
    

time_normal /= 1000
time_coo /= 1000
time_csc /= 1000
time_hess_coo /= 1000
time_hess_csc /= 1000

print(f"time_normal:  {time_normal}\t mem_normal : {mem_normal}" )
print("time_csc: ", time_csc)
print("time_coo: ", time_coo)
print("time_hess_coo: ", time_hess_coo)
print("time_hess_csc: ", time_hess_csc)



time_normal:  0.005069067478179931	 mem_normal : 0.016800000000000006
time_csc:  0.00010550808906555176
time_coo:  2.361607551574707e-05
time_hess_coo:  8.919239044189453e-07
time_hess_csc:  5.156993865966796e-07


In [60]:
# Test speed hstack with append

import numpy as np
import time

n = 200
m = 300

i = []
v = np.array([])

append_time = 0
stac_time = 0
for _ in range(100):
    i = []
    v = np.array([])
    tic = time.time()
    for _ in range(n):
        a = np.random.randint(10, 100)
        # concatenate
        i.extend(np.random.randint(0, 100, a))
    i = np.array(i)
    toc = time.time()


    append_time += toc - tic

    tic = time.time()
    for _ in range(n):
        a = np.random.randint(10, 100)
        v = np.hstack((v, np.random.randint(0, 100, a)))
    toc = time.time()

    stac_time += toc - tic

append_time += toc - tic

append_time /= 100
stac_time /= 100

print("append_time: ", append_time)
print("stac_time: ", stac_time)


append_time:  0.008751420974731446
stac_time:  0.011494379043579101


In [54]:
print(i)

[72 71 70 ... 18 90 48]


In [58]:

import numpy as np
from scipy.sparse import csc_matrix

# Sample data
face = [0, 1, 2, 3, 4, 5, 6, 7]
f = 2
cij = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
# Calculate the row indices (i)
i_indices = np.arange(len(face))

# Calculate the column indices (j)
j_indices = 3 * f + np.arange(3)

# Create the index grid using broadcasting
i_grid, j_grid = np.meshgrid(i_indices, j_indices, indexing='ij')

# Calculate the values using cij
val = cij[:, j_indices - 3 * f][i_indices]

# Create the CSC matrix using the calculated data
shape = (len(face), 3 * (f + 1))
J = csc_matrix((val, (i_grid, j_grid)), shape=shape)

# Print the resulting CSC matrix
print(J.toarray())


IndexError: index 2 is out of bounds for axis 0 with size 2

In [67]:
# Uncurry function 
X = np.arange(0,50)

indx = {"a": np.arange(0,10),
        "b": np.arange(10,20),
        "c": np.arange(20,30),
        }

def uncurry(X, v_idx):

    return [X[indx[k]] for k in v_idx]

a, b = uncurry(X, ["a", "b"])

print(a)
print(b)


[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [75]:
f=3
# Repeat the face indices 3 times [f1 f2 f3 f1 f2 f3 f1 f2 f3]
l = np.arange(3*f, 3*(f+1))
np.tile(l,3)

array([ 9, 10, 11,  9, 10, 11,  9, 10, 11])

In [99]:
import numpy as np

# Define the set of indices v
v = np.arange(0, 100)

# Define the list of indices f
f = [2, 4, 1, 6]

# Calculate the positions to extract and flatten the result
positions = np.array(f) * 3


# Create an array of indices to extract using NumPy's fancy indexing
indices_to_extract = np.repeat(positions, 3) + np.tile(np.arange(3), len(f))

print(f"positions: {positions}")
print(f"repeart : {np.repeat(positions, 3)}")
print(f"tile : {np.tile(np.arange(3), len(f))}")
print(f"indices_to_extract : {indices_to_extract}")
# Extract the values from v using fancy indexing
result = v[indices_to_extract]

print(result)


positions: [ 6 12  3 18]
repeart : [ 6  6  6 12 12 12  3  3  3 18 18 18]
tile : [0 1 2 0 1 2 0 1 2 0 1 2]
indices_to_extract : [ 6  7  8 12 13 14  3  4  5 18 19 20]
[ 6  7  8 12 13 14  3  4  5 18 19 20]


In [107]:
v = np.random.randint(0, 4, (4,3))

nf = np.array([0, 1, 2])

print(f" nf.v0: {nf@v[0]} \n nf.v1: {nf@v[1]} \n nf.v2: {nf@v[2]} \n nf.v3: {nf@v[3]} \n nf.v = {np.sum(nf*v, axis=1)}")


 nf.v0: 4 
 nf.v1: 9 
 nf.v2: 2 
 nf.v3: 7 
 nf.v = [4 9 2 7]


In [10]:
import numpy as np
from functools import reduce

v_idx = [[1,2],[3,4,5],[6,1,2,3],[1,2]]
c_v = [0, 1, 2, 3]

def concat(acc, ell):
    return np.hstack((acc, ell))

new_c = reduce( concat, [np.array([c_v[i]]).repeat(len(v_idx[i])) for i in range(len(v_idx)) ], np.array([]))

new_c

array([0., 0., 1., 1., 1., 2., 2., 2., 2., 3., 3.])

In [1]:
import numpy as np

v_idx = [[1, 2], [3, 4, 5], [6, 1, 2, 3], [1, 2]]
c_v = [0, 1, 2, 3]

# Create a list of repeated values from c_v based on v_idx
repeated_values = [np.array([c_v[i]] * len(sublist)) for i, sublist in enumerate(v_idx)]

# Concatenate the repeated values using numpy.concatenate
new_c = np.concatenate(repeated_values)

print(new_c)


[0 0 1 1 1 2 2 2 2 3 3]


In [5]:
import vedo as vd 

vd.settings.default_backend = 'k3d'

# Create a sphere
sphere = vd.Sphere(pos=(0, 0, 0), r=1, c='r')

# Create a plane (defined by a point on the plane and its normal vector)
plane = vd.Plane(
    pos=(0, 0, 0),
    normal=(0, 0, 1),
    s=(10, 10),
    res=(1, 1),
    c='gray5',
    alpha=0.8
)
# Cut the sphere with the plane

cut_sphere = sphere.cut_with_plane( origin=(0, 0, 0), normal=(0, 0, 1))
#cut_sphere2 = sphere.cut_with_plane( origin=(0, 0, 0), normal=(0, 0, 1), invert=True)


# Create a spline from the intersection points
#spline = vd.Spline(cut_sphere).c('blue').lw(5)

# Show the cut sphere and spline
vd.show(sphere, plane, axes=1)

Plot(antialias=True, axes=['x', 'y', 'z'], axes_helper=1.0, axes_helper_colors=[16711680, 65280, 255], backgro…

In [2]:
import numpy as np
# Given vector v
v = np.array([1, 3, 4, 2])

# Efficient generation of u
base_range = np.arange(3)
u = 3 * np.repeat(v, 3) + np.tile(base_range, len(v))
print(u)

[ 3  4  5  9 10 11 12 13 14  6  7  8]


In [4]:
v = np.array([0,1,2,3,4,5])
np.tile(v, 3)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [7]:
import numpy as np

# Example lists of vertices
v0 = [[1,0,0],[0,1,0],[0,0,1]]
v1 = [[2,0,2],[2,2,0],[0,2,2]]
v2 = [[0,0,3],[1,0,1],[2,1,10]]

# Convert lists to numpy arrays
v0_array = np.array(v0)
v1_array = np.array(v1)
v2_array = np.array(v2)

# Create list of matrices
matrices = [np.vstack((v0_array[i], v1_array[i], v2_array[i])) for i in range(len(v0_array))]

# Display one of the matrices as an example
print(matrices[0])
print(matrices[1])
print(matrices[2])


[[1 0 0]
 [2 0 2]
 [0 0 3]]
[[0 1 0]
 [2 2 0]
 [1 0 1]]
[[ 0  0  1]
 [ 0  2  2]
 [ 2  1 10]]


In [6]:
i = np.array([0, 3, 4])

indices = 3 * np.repeat(i, 3) + np.tile(range(3), len(i))
print(i)
print(indices)

[0 3 4]
[ 0  1  2  9 10 11 12 13 14]


In [3]:
nc = np.array([[0,1,0]])

x  = np.array([[1,0,0], [0,1,0], [0,0,2]])  

f = np.array([0,2])
print(np.linalg.norm(np.array([1,-1,0])))
print(np.linalg.norm(np.array([0,1,-2])))
np.linalg.norm(nc - x[f], axis=1)


1.4142135623730951
2.23606797749979


array([1.41421356, 2.23606798])

In [5]:
import os 
import sys

# Add hananLab to path
#path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(os.getcwd()))))
path = os.path.dirname(os.getcwd())
sys.path.append(path)

import igl
import polyscope as ps
import numpy as np


from hanan.geometry.mesh import Mesh
from hanan.geometry.utils import *
from hanan.optimization.Sphericity import Sphericity
from hanan.optimization.Optimizer import Optimizer

# Define paths
dir_path = os.getcwd()
data_path = dir_path+"/approximation/data/" # data path

k = 1
# Load test mesh
v, f = igl.read_triangle_mesh(os.path.join(data_path,  "test_remeshed_"+str(k)+".obj"))

n = igl.per_vertex_normals(v, f)

# Fix direction
signs = np.sign(np.sum(n * ([0,0,1]), axis=1))
n = n * signs[:, None]

# compute line congruence
e = 2.5 * n

# Compute second envelope
vv = v + e

i, j, k = f[:,0], f[:,1], f[:,2]
# Compute guess for sphere
ct, _, nt = circle_3pts(v[i], v[j], v[k])
ct2, _, _ = circle_3pts(vv[i], vv[j], vv[k])

# Compute sphere center
sph_c = -1/2*np.linalg.norm(ct2 - ct, axis=1)[:,None] * nt + ct

# Compute sphere radius
sph_r = np.linalg.norm(sph_c - v[0], axis=1)


nV = len(v)
nF = len(f)
# Set up Optimization


# Define variable indices
var_idx = {     "e"    : np.arange( 0            , 3*nV),  # Line congruence
                "sph_c": np.arange( 3*nV         , 3*nV +  3*nF), # Sphere centers
                "sph_r": np.arange( 3*nV +  3*nF , 3*nV +  4*nF) # Sphere radius
        }

# Init X 
X = np.zeros(sum(len(arr) for arr in var_idx.values()))

X[var_idx["e"]]      = e.flatten()
X[var_idx["sph_c"]]  = sph_c.flatten()
X[var_idx["sph_r"]]  = sph_r

# Init Sphericity
sphericity = Sphericity()
sphericity.initialize_constraint(X, var_idx, f, v)

# Init Line Cong


# Optimizer
optimizer = Optimizer()
optimizer.initialize_optimizer(X, var_idx, "LM", 0.5, 1)

it = 100
for _ in range(it):
    
    optimizer.get_gradients(sphericity)
    optimizer.optimize()

ne, nc, nr = optimizer.uncurry_X("e", "sph_c", "sph_r")

ne = ne.reshape((-1, 3))
nc = nc.reshape((-1, 3))

# Compute second envelope
vv = v + ne


# Compute sphericity 

for idx_f in range(len(f)):
    i_f = f[idx_f]         
    print(f"face: {idx_f}")
    sph_vv = np.zeros(3)
    sph_v  = np.zeros(3)
    for ni, i in enumerate(i_f):
        sph_vv[ni] = np.linalg.norm(vv[i] - nc[idx_f])
        sph_v[ni]  = np.linalg.norm(v[i] - nc[idx_f])
    print(f"sph_vv: {sph_vv}")
    print(f"sph_v: {sph_v}")
    
print("r", nr)


# Visualize
ps.init()
ps.remove_all_structures()


for _ in range(2):
    i = np.random.randint(0, len(sph_c)-1)
    c = sph_c[i] 
    sphere = ps.register_point_cloud(f"sphere_c{i}", np.array([c]), enabled=True, color=(0,0,0), transparency=0.5)
    sphere.set_radius(nr[i], relative=False)

ps.register_point_cloud("sphere_c", nc, enabled=True, radius=0.008, color=(0,0,0))
mesh = ps.register_surface_mesh("mesh", v, f)
mesh2 = ps.register_surface_mesh("mesh 2", vv, f)
mesh.add_vector_quantity("n", ne, length=1, enabled=True, vectortype="ambient", color=(1,0,0))
#mesh.add_vector_quantity("Circum normal", -nt, defined_on="faces", length=4, enabled=True, vectortype="ambient", color=(0,0,0))
#mesh.add_vector_quantity("Circum normal1", nt, defined_on="faces", length=4, enabled=True, vectortype="ambient", color=(0,0,0))

ps.show()

 E 1: 26887.948390274498	 dx: 16.684035364666475
 E 2: 8907.757431280412	 dx: 10.238934250156953
 E 3: 2915.189152079881	 dx: 6.382455572259097
 E 4: 934.042194262164	 dx: 3.971222088646615
 E 5: 293.56867001912815	 dx: 2.839979774309162
 E 6: 91.78303394854116	 dx: 2.1916188017910567
 E 7: 30.385825481925643	 dx: 1.644954434651291
 E 8: 11.163091061069569	 dx: 1.0916392487367153
 E 9: 4.163842374088999	 dx: 0.6478414070242166
 E 10: 1.45702909647199	 dx: 0.36747519347599505
 E 11: 0.48063215655676295	 dx: 0.2062525248708147
 E 12: 0.17661583853647136	 dx: 0.12428786225618109
 E 13: 0.06396566469735794	 dx: 0.07464146647037731
 E 14: 0.022960094341034902	 dx: 0.04469625953868306
 E 15: 0.008196335991887547	 dx: 0.026707328655382674
 E 16: 0.002916227295444866	 dx: 0.015935304546360732
 E 17: 0.0010355052616781435	 dx: 0.009499213147581892
 E 18: 0.0003672491729540196	 dx: 0.005659337321314157
 E 19: 0.00013015378703221965	 dx: 0.0033704838253081114
 E 20: 4.610692606221682e-05	 dx: 0.0