In [ ]:
import numpy as np

## Determinant

In [ ]:
# Generate 5 random points in 3D
v1 = np.random.rand(5,3)
v2 = np.random.rand(5,3)
v3 = np.random.rand(5,3)

# Compute the determinant of the matrix formed by the vectors (v1, v2, v3) for each row
# The determinant is zero if the vectors are coplanar
cross = np.cross(v2, v3)


dets = np.sum(v1 * cross, axis=1)
print(f"Full Determiant : {dets}")
print(f"Det 0 : {np.linalg.det(np.array([v2[0], v3[0], v1[0]]))}")
print(f"Det 1 : {np.linalg.det(np.array([v2[1], v3[1], v1[1]]))}")
print(f"Det 2 : {np.linalg.det(np.array([v2[2], v3[2], v1[2]]))}")

## $v_{ij} \cdot (v_{ik} \times \partial e_c)*det2$

In [ ]:
import numpy as np
import time

# Define the size of the matrices and vectors
n = 800  # Large number of rows
m = 3  # Number of columns
T = 200  # Number of repetitions

# Initialize variables to store total elapsed times
total_time_1 = 0
total_time_2 = 0


for t in range(T):
    # Generate random matrices and vectors
    eik = np.random.rand(n, m)
    derx = np.zeros((n, m))
    derx[:, 0] = 1
    nc = np.random.rand(n)

    print("init eik: \n", eik[:5])

    # Benchmark the first approach
    start_time = time.time()
    eikXdec_x_1 = np.cross(eik, derx) / nc[:, None]
    elapsed_time_1 = time.time() - start_time

    # Benchmark the second approach
    start_time = time.time()
    eikXdec_x_2 = eik[:, [0, 2, 1]] / nc[:, None]
    eikXdec_x_2[:, 0] = 0
    eikXdec_x_2[:, 1] *= -1  
    eikXdec_x_2 *= -1
    elapsed_time_2 = time.time() - start_time

    total_time_1 += elapsed_time_1
    total_time_2 += elapsed_time_2

    print("final eik: \n", eik[:5])
    print("*-----------------------------*")

    # asssert same
    assert(np.allclose(eikXdec_x_1, eikXdec_x_2))
    
total_time_1 /= T
total_time_2 /= T

# Print the elapsed times
print("Elapsed time for approach 1:", total_time_1, "seconds")
print("Elapsed time for approach 2:", total_time_2, "seconds")

In [ ]:
# 5 Random points
v1 = np.random.rand(5,3)
# 3 random faces indices
f1 = np.random.randint(0, 5, 3)

np.sum(v1[f1], axis=1)

In [ ]:
import numpy as np

n= 5
m= 6
J = np.zeros((n,m))
v = np.ones(3)
J[2:n, 3: 6] = v * np.eye(3)
print(J)

J[:3, 0:3] = np.diag(v)
print(J)


In [ ]:
import numpy as np
import time

n= 8
m= 8

J = np.repeat([0,1,2,3,4,5,6,7,8], 9).reshape((9,9)).T
i = 3*np.array([1, 2, 0, 1, 2, 0, 1, 2])
v = np.array([10, 20, 30, 10, 40, 50, 60, 2])
J[range(m), i] = v
print(J)

In [ ]:
def cross_id(v, coord, type=0):
    """ Function tha retunr the cross product with coordinate vectors like [1, 0, 0], [0, 1, 0], [0, 0, 1]
        type 0
        V x [1,0,0]
        type 1
        [1,0,0] x V

    """

    if coord=='x':
        cross = v[:, [0, 2, 1]] 
        cross[:, 0] = 0
        cross[:, 2] *= -1 
    elif coord=='y':
        cross = v[:, [2, 1, 0]]
        cross[:, 0] *= -1
        cross[:, 1] = 0
    elif coord=='z':
        cross = v[:, [1, 0, 2]]
        cross[:, 1] *= -1
        cross[:, 2] = 0
    
    if type==1:
        cross *= -1

    return cross

In [ ]:
v = np.random.rand(1000000, 3)

# Test time
id_time = 0
cross_time = 0
for i in range(500):
    s = time.time()
    id_c =  cross_id(v/3, 'x', 1)
    id_time += time.time() - s

    s = time.time()
    cr = np.cross(np.array([1, 0, 0]),v/3)
    cross_time += time.time() - s

    assert(np.allclose(id_c, cr))

print("average id_time: ", id_time/100)

print("average cross_time: ", cross_time/100)


In [ ]:
# Compute the edge vectors per each face
n = 4
vj = np.array([[1, 1,1], [2, 2,2], [3, 3,3], [4, 4,4]])
vi = np.array([[0, 1,0], [0, 0,0], [0, 0,0], [0, 0,0]])
vk = np.array([[10, 10, 10], [20, 20,20], [30, 30,30], [40, 40,40]])
fvij = np.empty((n, 2, 3), dtype=float)

# Compute the edge vectors per each face
fvij[:,0] = vj - vi
fvij[:,1] = vk - vi
print(fvij[:,0])

In [ ]:
np.sum( np.array([1,0,1])*vj, axis=1)

In [ ]:
import numpy as np
face = np.array([0,3,5,1])
n = 6
m = 10
nli = 3
ei = np.array([[1,0,0],[0,1,0],[0,0,1]])
f = 1
ni = np.array([[1,2,3],[10,11,12],[4,5,6],[3,5,7]])
norms = np.array([[1,2,3,4],[5,6,7,8]])
J = np.zeros((n,m))

i = 1


J[range(i,i + len(face)), nli + face] = -np.sum( ei[f]*ni, axis=1)/norms[0, None]

print(J,-np.sum( ei[f]*ni, axis=1)/norms[0, None])

In [ ]:
import time 
import numpy as np

n = 1000
m = 1000
J = np.zeros((n,m))

a = 20
b = a*3
nt = np.random.randint(0, n, a)
v  = np.arange(0, b)
v1 = np.arange(0, b).reshape((20, 3))


tm  = 0
tm1 = 0
for i in range(1000):
    vals = np.random.rand(20,3)
    
    
    tic = time.time()
    J [nt.repeat(3), v] = vals.flatten()
    tm += time.time() - tic

    tic = time.time()
    J[nt, v1[:,0]] = vals[:,0]
    J[nt, v1[:,1]] = vals[:,1]
    J[nt, v1[:,2]] = vals[:,2]
    tm1 += time.time() - tic


tm /= 1000
tm1 /= 1000
print("tm: ", tm)
print("tm1: ", tm1)


In [ ]:
# Test construction of sparse matrix

# 1) Create a normal matrix J and then convert it to csc_matrix


import numpy as np
import time
from scipy.sparse import csc_matrix, coo_matrix
# Measure memory usage
import psutil


n = 1000
m = 2000

time_normal = 0
time_coo = 0
time_csc = 0
time_hess_coo = 0
time_hess_csc = 0

for _ in range(200):

    
    # Random columns
    cols = np.random.randint(0, m, 200)
    # Random rows
    rows = np.random.randint(0, n, 200)

    # Random values
    vals = np.random.rand(200)


    # Fill the matrix normal
    # Take time and memory usage
    tic = time.time()
    
    J = np.zeros((n,m))
    J[rows, cols] = vals
    J_sparse = csc_matrix(J)
    
    toc = time.time()

    
    time_normal += toc - tic


    # Fill the matrix csc
    tic = time.time()
    J_sparse_csc = csc_matrix((vals, (rows, cols)), shape=(n, m))
    toc = time.time()

    time_csc += toc - tic

    tic = time.time()
    h = (J_sparse_csc.T * J_sparse_csc).tocsr()
    toc = time.time()

    time_hess_csc = toc - tic

    # Fill matrix coo
    tic = time.time()
    J_sparse_coo = coo_matrix((vals, (rows, cols)), shape=(n, m))
    toc = time.time()

    time_coo += toc - tic

    tic = time.time()
    h = (J_sparse_coo.T * J_sparse_coo).tocsr()
    toc = time.time()

    time_hess_coo = toc - tic
    

time_normal /= 1000
time_coo /= 1000
time_csc /= 1000
time_hess_coo /= 1000
time_hess_csc /= 1000

print(f"time_normal:  {time_normal}\t mem_normal : {mem_normal}" )
print("time_csc: ", time_csc)
print("time_coo: ", time_coo)
print("time_hess_coo: ", time_hess_coo)
print("time_hess_csc: ", time_hess_csc)



In [ ]:
# Test speed hstack with append

import numpy as np
import time

n = 200
m = 300

i = []
v = np.array([])

append_time = 0
stac_time = 0
for _ in range(100):
    i = []
    v = np.array([])
    tic = time.time()
    for _ in range(n):
        a = np.random.randint(10, 100)
        # concatenate
        i.extend(np.random.randint(0, 100, a))
    i = np.array(i)
    toc = time.time()


    append_time += toc - tic

    tic = time.time()
    for _ in range(n):
        a = np.random.randint(10, 100)
        v = np.hstack((v, np.random.randint(0, 100, a)))
    toc = time.time()

    stac_time += toc - tic

append_time += toc - tic

append_time /= 100
stac_time /= 100

print("append_time: ", append_time)
print("stac_time: ", stac_time)


In [ ]:
print(i)

In [ ]:

import numpy as np
from scipy.sparse import csc_matrix

# Sample data
face = [0, 1, 2, 3, 4, 5, 6, 7]
f = 2
cij = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
# Calculate the row indices (i)
i_indices = np.arange(len(face))

# Calculate the column indices (j)
j_indices = 3 * f + np.arange(3)

# Create the index grid using broadcasting
i_grid, j_grid = np.meshgrid(i_indices, j_indices, indexing='ij')

# Calculate the values using cij
val = cij[:, j_indices - 3 * f][i_indices]

# Create the CSC matrix using the calculated data
shape = (len(face), 3 * (f + 1))
J = csc_matrix((val, (i_grid, j_grid)), shape=shape)

# Print the resulting CSC matrix
print(J.toarray())


In [ ]:
# Uncurry function 
X = np.arange(0,50)

indx = {"a": np.arange(0,10),
        "b": np.arange(10,20),
        "c": np.arange(20,30),
        }

def uncurry(X, v_idx):

    return [X[indx[k]] for k in v_idx]

a, b = uncurry(X, ["a", "b"])

print(a)
print(b)


In [ ]:
f=3
# Repeat the face indices 3 times [f1 f2 f3 f1 f2 f3 f1 f2 f3]
l = np.arange(3*f, 3*(f+1))
np.tile(l,3)

In [ ]:
import numpy as np

# Define the set of indices v
v = np.arange(0, 100)

# Define the list of indices f
f = [2, 4, 1, 6]

# Calculate the positions to extract and flatten the result
positions = np.array(f) * 3


# Create an array of indices to extract using NumPy's fancy indexing
indices_to_extract = np.repeat(positions, 3) + np.tile(np.arange(3), len(f))

print(f"positions: {positions}")
print(f"repeart : {np.repeat(positions, 3)}")
print(f"tile : {np.tile(np.arange(3), len(f))}")
print(f"indices_to_extract : {indices_to_extract}")
# Extract the values from v using fancy indexing
result = v[indices_to_extract]

print(result)


In [ ]:
v = np.random.randint(0, 4, (4,3))

nf = np.array([0, 1, 2])

print(f" nf.v0: {nf@v[0]} \n nf.v1: {nf@v[1]} \n nf.v2: {nf@v[2]} \n nf.v3: {nf@v[3]} \n nf.v = {np.sum(nf*v, axis=1)}")


In [ ]:
import numpy as np
from functools import reduce

v_idx = [[1,2],[3,4,5],[6,1,2,3],[1,2]]
c_v = [0, 1, 2, 3]

def concat(acc, ell):
    return np.hstack((acc, ell))

new_c = reduce( concat, [np.array([c_v[i]]).repeat(len(v_idx[i])) for i in range(len(v_idx)) ], np.array([]))

new_c

In [ ]:
import numpy as np

v_idx = [[1, 2], [3, 4, 5], [6, 1, 2, 3], [1, 2]]
c_v = [0, 1, 2, 3]

# Create a list of repeated values from c_v based on v_idx
repeated_values = [np.array([c_v[i]] * len(sublist)) for i, sublist in enumerate(v_idx)]

# Concatenate the repeated values using numpy.concatenate
new_c = np.concatenate(repeated_values)

print(new_c)


In [ ]:
import vedo as vd 

vd.settings.default_backend = 'k3d'

# Create a sphere
sphere = vd.Sphere(pos=(0, 0, 0), r=1, c='r')

# Create a plane (defined by a point on the plane and its normal vector)
plane = vd.Plane(
    pos=(0, 0, 0),
    normal=(0, 0, 1),
    s=(10, 10),
    res=(1, 1),
    c='gray5',
    alpha=0.8
)
# Cut the sphere with the plane

cut_sphere = sphere.cut_with_plane( origin=(0, 0, 0), normal=(0, 0, 1))
#cut_sphere2 = sphere.cut_with_plane( origin=(0, 0, 0), normal=(0, 0, 1), invert=True)


# Create a spline from the intersection points
#spline = vd.Spline(cut_sphere).c('blue').lw(5)

# Show the cut sphere and spline
vd.show(sphere, plane, axes=1)

In [ ]:
import numpy as np
# Given vector v
v = np.array([1, 3, 4, 2])

# Efficient generation of u
base_range = np.arange(3)
u = 3 * np.repeat(v, 3) + np.tile(base_range, len(v))
print(u)

In [ ]:
v = np.array([0,1,2,3,4,5])
np.tile(v, 3)

In [ ]:
import numpy as np

# Example lists of vertices
v0 = [[1,0,0],[0,1,0],[0,0,1]]
v1 = [[2,0,2],[2,2,0],[0,2,2]]
v2 = [[0,0,3],[1,0,1],[2,1,10]]

# Convert lists to numpy arrays
v0_array = np.array(v0)
v1_array = np.array(v1)
v2_array = np.array(v2)

# Create list of matrices
matrices = [np.vstack((v0_array[i], v1_array[i], v2_array[i])) for i in range(len(v0_array))]

# Display one of the matrices as an example
print(matrices[0])
print(matrices[1])
print(matrices[2])


In [ ]:
i = np.array([0, 3, 4])

indices = 3 * np.repeat(i, 3) + np.tile(range(3), len(i))
print(i)
print(indices)

In [ ]:
nc = np.array([[0,1,0]])

x  = np.array([[1,0,0], [0,1,0], [0,0,2]])  

f = np.array([0,2])
print(np.linalg.norm(np.array([1,-1,0])))
print(np.linalg.norm(np.array([0,1,-2])))
np.linalg.norm(nc - x[f], axis=1)


In [ ]:
import os 
import sys

# Add hananLab to path
#path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(os.getcwd()))))
path = os.path.dirname(os.getcwd())
sys.path.append(path)

import igl
import polyscope as ps
import numpy as np


from hanan.geometry.mesh import Mesh
from hanan.geometry.utils import *
from hanan.optimization.Sphericity import Sphericity
from hanan.optimization.Optimizer import Optimizer
from hanan.optimization.LineCong import LineCong
from hanan.optimization.LineCong_Fairness import LineCong_Fair
from hanan.optimization.Torsal import Torsal

# Define paths
dir_path = os.getcwd()
data_path = dir_path+"/approximation/data/" # data path

# Load test mesh
v, f = igl.read_triangle_mesh(os.path.join(data_path, "New_Tri_mesh.obj"))

n = igl.per_vertex_normals(v, f)

# Create mesh
mesh = Mesh()
mesh.make_mesh(v, f)

# Compute mesh properties
dual_top          = mesh.vertex_ring_faces_list()
inner_vertices    = mesh.inner_vertices()
vertex_adj        = mesh.vertex_adjacency_list()
boundary_faces    = mesh.boundary_faces()
boundary_vertices = mesh.boundary_vertices()
inner_edges       = mesh.inner_edges()

# Get vertex indices of each edge
ed_i, ed_j = mesh.edge_vertices()

# Get oposite vertex indices of each edge
ed_k, ed_l = mesh.edge_oposite_vertices()


# Fix direction
signs = np.sign(np.sum(n * ([0,0,-1]), axis=1))
n = n * signs[:, None]

# compute line congruence
e = 10 * n

# Compute second envelope
vv = v + e

# Compute indices of vertices of each face
i, j, k = f[:,0], f[:,1], f[:,2]


# Compute guess for sphere
ct, _, nt = circle_3pts(v[i], v[j], v[k])
ct2, _, nt2 = circle_3pts(vv[i], vv[j], vv[k])


for bf in boundary_faces:
    for bv in f[bf]:
        if bv in boundary_vertices:
            n[bv] = nt[bf]
            np.delete(boundary_vertices, np.where(boundary_vertices == bv))


vc  = np.sum(v[f], axis=1)/3
vvc = np.sum(vv[f], axis=1)/3


# Compute sphere center
signs = np.sign(np.sum(nt * ([0,0,-1]), axis=1))
nt = nt * signs[:, None]

sph_c = ct + 0.5*np.linalg.norm(ct2 - ct,axis=1)[:,None]*nt


# Compute sphere radius
sph_r = np.linalg.norm(sph_c - v[i], axis=1)

# Compute number of variables
nV = len(v)
nF = len(f)
nIE = len(inner_edges)


# Define variable indices
var_idx = {     "e"     : np.arange( 0            , 3*nV),  # Line congruence
                "sph_c" : np.arange( 3*nV         , 3*nV +  3*nF),  # Sphere centers
                "sph_r" : np.arange( 3*nV +  3*nF , 3*nV +  4*nF),  # Sphere radius
                "th"    : np.arange( 3*nV +  4*nF , 3*nV +  5*nF),  # theta  angle <t1, vji
                "phi"   : np.arange( 3*nV +  5*nF , 3*nV +  6*nF),  # phi  angel < t1, t2
                "nt1"   : np.arange( 3*nV +  6*nF , 3*nV +  9*nF),  # Normal torsal plane t1 
                "nt2"   : np.arange( 3*nV +  9*nF , 3*nV +  12*nF),  # Normal torsal plane t2
                "u"     : np.arange( 3*nV +  12*nF , 3*nV + 12*nF + 3*nIE)  # Normal torsal plane t2
        }

# Init X 
X = np.zeros(sum(len(arr) for arr in var_idx.values()))

X[var_idx["e"]]      = e.flatten()
X[var_idx["sph_c"]]  = sph_c.flatten()
X[var_idx["sph_r"]]  = sph_r

t1, t2, a1, a2, b, validity = solve_torsal(v[i], v[j], v[k] , e[i], e[j], e[k])

tt1 = unit(a1[:,None]*(vv[j] - vv[i]) + b[:,None]*(vv[k] - vv[i]))
tt2 = unit(a2[:,None]*(vv[j] - vv[i]) + b[:,None]*(vv[k] - vv[i]))

ec = np.sum(e[f], axis=1)/3

# Init Sphericity
sphericity = Sphericity()
sphericity.initialize_constraint(X, var_idx, f, v)

# Init Line Congruence Fairnes
line_fair = LineCong_Fair()
line_fair.initialize_constraint(X, var_idx, vertex_adj, inner_vertices) 
line_fair.set_weigth(0.001)

# Init Line Cong
linecong = LineCong()
linecong.initialize_constraint(X, var_idx, len(v),  dual_top, inner_vertices)

# Init Torsal 
torsal = Torsal()
torsal.initialize_constraint(X, var_idx, v, f)

#  Optimizer
optimizer = Optimizer()
optimizer.initialize_optimizer(X, var_idx, "LM", 0.5, 1)


it = 60
for _ in range(it):
    optimizer.unitize_variable("nt1", 3)
    optimizer.unitize_variable("nt2", 3)
    
    optimizer.get_gradients(sphericity)
    optimizer.get_gradients(linecong)
    optimizer.get_gradients(torsal)
    optimizer.get_gradients(line_fair)
    optimizer.optimize()






In [ ]:
## Extract variables
ne, nc, nr, th, phi = optimizer.uncurry_X("e", "sph_c", "sph_r", "th", "phi")

ne = ne.reshape((-1,3))
nc = nc.reshape((-1,3))

vv = v + ne
i, j, k = f[:,0], f[:,1], f[:,2]
vi, vj, vk = v[i], v[j], v[k]

vij = vj - vi 
vki = vk - vi

t1 = unit( np.cos(th)[:,None]*vij +  np.sin(th)[:,None]*vki)
t2 = unit(np.cos(th + phi)[:,None]*vij + np.sin(th + phi)[:,None]*vki)

tt1 = unit( np.cos(th)[:,None]*(vv[j] - vv[i]) +  np.sin(th)[:,None]*(vv[k] - vv[i]))
tt2 = unit(np.cos(th + phi)[:,None]*(vv[j] - vv[i]) + np.sin(th + phi)[:,None]*(vv[k] - vv[i]))

# Compute planarity
planarity1 = planarity_check(t1, tt1, ec)

planarity2 = planarity_check(t2, tt2, ec)

avg_planarity = (planarity1 + planarity2)/2
## Visualize
ps.init()
ps.remove_all_structures()

# Show boundary spheres
for id in range(len(boundary_faces)):
    i = boundary_faces[id]
    c = nc[i] 
    sphere = ps.register_point_cloud(f"sphere_c{i}", np.array([c]), enabled=True, color=(0,0,0), transparency=0.5)
    sphere.set_radius(nr[i], relative=False)



ps.register_point_cloud("cr", ct, enabled=True, radius=0.001, color=(0,0,0))
mesh = ps.register_surface_mesh("mesh", v, f)
mesh2 = ps.register_surface_mesh("mesh 2", vv, f)
mesh.add_vector_quantity("n", ne, length=1, enabled=True, vectortype="ambient", radius=0.0005, color=(0,0,0))


# Show sphere circumcircle axis
#mesh.add_vector_quantity(  "n",   nt, defined_on="faces", length=0.5, radius=0.0005, enabled=True,  color=(0.5,0,0.8))
#mesh2.add_vector_quantity("n2", -nt2, defined_on="faces", length=0.5, radius=0.0005, enabled=True,  color=(0,0.5,0))

# Visualize sphere radius as scalar quantity
mesh.add_scalar_quantity("radius sphere", nr, defined_on="faces", enabled=True, cmap="coolwarm")

# Visualize planarity as scalar quantity
mesh.add_scalar_quantity("planarity1", planarity1, defined_on="faces", enabled=True, cmap="coolwarm")
mesh.add_scalar_quantity("planarity2", planarity2, defined_on="faces", enabled=True, cmap="coolwarm")
mesh.add_scalar_quantity("Avg planarity", avg_planarity, defined_on="faces", enabled=True, cmap="coolwarm")
mesh.add_scalar_quantity("Validity", validity, defined_on="faces", enabled=True, cmap="jet")

mesh.add_vector_quantity("t1", t1, defined_on="faces", length=0.01, enabled=True,  color=(1,1,1))
mesh.add_vector_quantity("t2", t2, defined_on="faces", length=0.01, enabled=True,  color=(0,0,0))
#mesh.add_vector_quantity("Circum normal", -nt, defined_on="faces", length=4, enabled=True, vectortype="ambient", color=(0,0,0))
#mesh.add_vector_quantity("Circum normal1", nt, defined_on="faces", length=4, enabled=True, vectortype="ambient", color=(0,0,0))

ps.show()

In [ ]:
v = np.array([1,2,3,4,5,6])

3 * np.repeat(v, 3) + np.tile(range(3), len(v))

In [ ]:
## Extract variables
ne, nc, nr, th, phi = optimizer.uncurry_X("e", "sph_c", "sph_r", "th", "phi")

ne = ne.reshape((-1,3))
nc = nc.reshape((-1,3))

vv = v + ne
i, j, k = f[:,0], f[:,1], f[:,2]
vi, vj, vk = v[i], v[j], v[k]

vij = vj - vi 
vki = vk - vi

t1 = unit( np.cos(th)[:,None]*vij +  np.sin(th)[:,None]*vki)
t2 = unit(np.cos(th + phi)[:,None]*vij + np.sin(th + phi)[:,None]*vki)

tt1 = unit( np.cos(th)[:,None]*(vv[j] - vv[i]) +  np.sin(th)[:,None]*(vv[k] - vv[i]))
tt2 = unit(np.cos(th + phi)[:,None]*(vv[j] - vv[i]) + np.sin(th + phi)[:,None]*(vv[k] - vv[i]))

# Compute planarity
planarity1 = planarity_check(t1, tt1, ec)

planarity2 = planarity_check(t2, tt2, ec)

avg_planarity = (planarity1 + planarity2)/2
## Visualize
ps.init()
ps.remove_all_structures()

# Show boundary spheres
for id in range(len(boundary_faces)):
    i = boundary_faces[id]
    c = nc[i] 
    sphere = ps.register_point_cloud(f"sphere_c{i}", np.array([c]), enabled=True, color=(0,0,0), transparency=0.5)
    sphere.set_radius(nr[i], relative=False)



ps.register_point_cloud("cr", ct, enabled=True, radius=0.001, color=(0,0,0))
mesh = ps.register_surface_mesh("mesh", v, f)
mesh2 = ps.register_surface_mesh("mesh 2", vv, f)
mesh.add_vector_quantity("n", ne, length=1, enabled=True, vectortype="ambient", radius=0.0005, color=(0,0,0))


# Show sphere circumcircle axis
#mesh.add_vector_quantity(  "n",   nt, defined_on="faces", length=0.5, radius=0.0005, enabled=True,  color=(0.5,0,0.8))
#mesh2.add_vector_quantity("n2", -nt2, defined_on="faces", length=0.5, radius=0.0005, enabled=True,  color=(0,0.5,0))

# Visualize sphere radius as scalar quantity
mesh.add_scalar_quantity("radius sphere", nr, defined_on="faces", enabled=True, cmap="coolwarm")

# Visualize planarity as scalar quantity
mesh.add_scalar_quantity("planarity1", planarity1, defined_on="faces", enabled=True, cmap="coolwarm")
mesh.add_scalar_quantity("planarity2", planarity2, defined_on="faces", enabled=True, cmap="coolwarm")
mesh.add_scalar_quantity("Avg planarity", avg_planarity, defined_on="faces", enabled=True, cmap="coolwarm")
mesh.add_scalar_quantity("Validity", validity, defined_on="faces", enabled=True, cmap="jet")

mesh.add_vector_quantity("t1", t1, defined_on="faces", length=0.01, enabled=True,  color=(1,1,1))
mesh.add_vector_quantity("t2", t2, defined_on="faces", length=0.01, enabled=True,  color=(0,0,0))
#mesh.add_vector_quantity("Circum normal", -nt, defined_on="faces", length=4, enabled=True, vectortype="ambient", color=(0,0,0))
#mesh.add_vector_quantity("Circum normal1", nt, defined_on="faces", length=4, enabled=True, vectortype="ambient", color=(0,0,0))

ps.show()

In [ ]:
v = np.random.rand(4,3)
u = np.random.rand(4,3)

uv = vec_dot(u, v)
vv = vec_dot(v, v)

p = u - (uv/vv)[:,None]*v

vec_dot(p, v)



In [ ]:
3*np.arange(0, 3)+1

In [ ]:
import os 
import sys

# Add hananLab to path
#path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(os.getcwd()))))
path = os.path.dirname(os.getcwd())
sys.path.append(path)

import igl
import polyscope as ps
import numpy as np


from hanan.geometry.mesh import Mesh
from hanan.geometry.utils import *
from hanan.optimization.Sphericity import Sphericity
from hanan.optimization.Optimizer import Optimizer
from hanan.optimization.LineCong import LineCong
from hanan.optimization.LineCong_Fairness import LineCong_Fair
from hanan.optimization.Torsal import Torsal
from hanan.optimization.Torsal_fairness import Torsal_Fair


# Define paths
dir_path = os.getcwd()
data_path = dir_path+"/approximation/data/" # data path

# Load test mesh
#v, f = igl.read_triangle_mesh(os.path.join(data_path, "New_Tri_mesh.obj"))

# fix seed
np.random.seed(0)
v = np.random.rand(4,3)
f = np.array([[0,1,2], [0,2,3]])

n = igl.per_vertex_normals(v, f)

# Create mesh
mesh = Mesh()
mesh.make_mesh(v, f)

# Compute mesh properties
dual_top          = mesh.vertex_ring_faces_list()
inner_vertices    = mesh.inner_vertices()
vertex_adj        = mesh.vertex_adjacency_list()
boundary_faces    = mesh.boundary_faces()
boundary_vertices = mesh.boundary_vertices()
inner_edges       = mesh.inner_edges()

# Get vertex indices of each edge
ed_i, ed_j = mesh.edge_vertices()

ed_i = ed_i[inner_edges]
ed_j = ed_j[inner_edges]

# Get oposite vertex indices of each edge
ed_k, ed_l = mesh.edge_oposite_vertices()

ed_k = ed_k[inner_edges]
ed_l = ed_l[inner_edges]

print(f"ed_i: {ed_i}")
print(f"ed_j: {ed_j}")
print(f"ed_k: {ed_k}")
print(f"ed_l: {ed_l}")

# Fix direction
signs = np.sign(np.sum(n * ([0,0,-1]), axis=1))
n = n * signs[:, None]

# compute line congruence
e = 5 * n

# Compute second envelope
vv = v + e

# Compute indices of vertices of each face
i, j, k = f[:,0], f[:,1], f[:,2]


# Compute guess for sphere
ct, _, nt = circle_3pts(v[i], v[j], v[k])
ct2, _, nt2 = circle_3pts(vv[i], vv[j], vv[k])


for bf in boundary_faces:
    for bv in f[bf]:
        if bv in boundary_vertices:
            n[bv] = nt[bf]
            np.delete(boundary_vertices, np.where(boundary_vertices == bv))


vc  = np.sum(v[f], axis=1)/3
vvc = np.sum(vv[f], axis=1)/3


# Compute sphere center
signs = np.sign(np.sum(nt * ([0,0,-1]), axis=1))
nt = nt * signs[:, None]

sph_c = ct + 0.5*np.linalg.norm(ct2 - ct,axis=1)[:,None]*nt


# Compute sphere radius
sph_r = np.linalg.norm(sph_c - v[i], axis=1)

# Compute number of variables
nV = len(v)
nF = len(f)
nIE = len(inner_edges)


# Define variable indices
var_idx = {     "e"     : np.arange( 0            , 3*nV),  # Line congruence
                "sph_c" : np.arange( 3*nV         , 3*nV +  3*nF),  # Sphere centers
                "sph_r" : np.arange( 3*nV +  3*nF , 3*nV +  4*nF),  # Sphere radius
                "th"    : np.arange( 3*nV +  4*nF , 3*nV +  5*nF),  # theta  angle <t1, vji
                "phi"   : np.arange( 3*nV +  5*nF , 3*nV +  6*nF),  # phi  angel < t1, t2
                "nt1"   : np.arange( 3*nV +  6*nF , 3*nV +  9*nF),  # Normal torsal plane t1 
                "nt2"   : np.arange( 3*nV +  9*nF , 3*nV +  12*nF),  # Normal torsal plane t2
                "u"     : np.arange( 3*nV +  12*nF , 3*nV + 12*nF + 3*nIE)  # Normal torsal plane t2
        }



# Init X 
X = np.zeros(sum(len(arr) for arr in var_idx.values()))

print(len(X))
print(3*nV + 12*nF + 3*nIE)
print(var_idx["u"][3*i])

X[var_idx["e"]]      = e.flatten()
X[var_idx["sph_c"]]  = sph_c.flatten()
X[var_idx["sph_r"]]  = sph_r

t1, t2, a1, a2, b, validity = solve_torsal(v[i], v[j], v[k] , e[i], e[j], e[k])

tt1 = unit(a1[:,None]*(vv[j] - vv[i]) + b[:,None]*(vv[k] - vv[i]))
tt2 = unit(a2[:,None]*(vv[j] - vv[i]) + b[:,None]*(vv[k] - vv[i]))

ec = np.sum(e[f], axis=1)/3

# Init Sphericity
sphericity = Sphericity()
sphericity.initialize_constraint(X, var_idx, f, v)

# Init Line Congruence Fairnes
line_fair = LineCong_Fair()
line_fair.initialize_constraint(X, var_idx, vertex_adj, inner_vertices) 
line_fair.set_weigth(0.001)

# Init Line Cong
linecong = LineCong()
linecong.initialize_constraint(X, var_idx, len(v),  dual_top, inner_vertices)

# Init Torsal 
torsal = Torsal()
torsal.initialize_constraint(X, var_idx, v, f)

# Init Torsal 
torsal_fair = Torsal_Fair()
torsal_fair.initialize_constraint(X, var_idx, v, e, inner_edges, ed_i, ed_j, ed_k, ed_l)

#  Optimizer
optimizer = Optimizer()
optimizer.initialize_optimizer(X, var_idx, "LM", 0.5, 1)


it = 60
for _ in range(it):
    # optimizer.unitize_variable("nt1", 3)
    # optimizer.unitize_variable("nt2", 3)
    
    # optimizer.get_gradients(sphericity)
    # optimizer.get_gradients(linecong)
    # optimizer.get_gradients(torsal)
    # optimizer.get_gradients(line_fair)
    optimizer.get_gradients(torsal_fair)
    optimizer.optimize()




In [1]:
import igl
import polyscope as ps
import numpy as np

v, f=igl.read_triangle_mesh("/Users/cisneras/Darboux_Transformation_Data/DT1_tri.obj")

spheres = np.loadtxt("/Users/cisneras/Darboux_Transformation_Data/sph_tri.dat",  dtype=float, delimiter="\t")


ps.init()
ps.remove_all_structures()

for _ in range(10):
    i = np.random.randint(0, len(f))
    sph = spheres[i]
    ps.register_point_cloud(f"sphere_{i}", np.array([sph[0:3]]), enabled=True, color=(0,0,0), transparency=0.5)
    ps.get_point_cloud(f"sphere_{i}").set_radius(sph[3], relative=False)
ps.register_surface_mesh("mesh", v, f)
ps.show()



[polyscope] Backend: openGL3_glfw -- Loaded openGL version: 4.1 Metal - 88


In [1]:
import os 
import sys

path = os.path.dirname(os.getcwd())
sys.path.append(path)

import igl
import polyscope as ps
import numpy as np


from hanan.geometry.mesh import Mesh
from hanan.geometry.utils import *
from hanan.optimization.Sphericity import Sphericity
from hanan.optimization.Optimizer import Optimizer
from hanan.optimization.LineCong import LineCong
from hanan.optimization.LineCong_Fairness import LineCong_Fair
from hanan.optimization.Torsal import Torsal
from hanan.optimization.Torsal_fairness import Torsal_Fair

import igl
import polyscope as ps
import numpy as np

v, f=igl.read_triangle_mesh("/Users/cisneras/hanan/hananLab/TriMesh_start.obj")

mesh = Mesh()
mesh.make_mesh(v, f)

face_neighbors = mesh.face_face_adjacency_list()

file_export = open("/Users/cisneras/hanan/hananLab/TriMesh_face_neighbors.dat", "w")

# Export face neighbors to .dat file
for i in range(len(face_neighbors)):
    for j in range(len(face_neighbors[i])-1):
        file_export.write(f"{face_neighbors[i][j]}\t")
    file_export.write(f"{face_neighbors[i][-1]}\n")

file_export.close()

Mesh Data Structure: |V| = 247, |F| = 435, |E| = 681


  o TriMesh_start


In [23]:
import numpy as np
import igl 
import meshplot as mp
import polyscope as ps  
import os
import sys

path = os.path.dirname(os.getcwd())
sys.path.append(path)

from hanan.geometry.utils import initialize_Line_Congruence, unit
from hanan.geometry.mesh import Mesh

# Define the center and radius of the hexagon

radius = 2
offset = 1
center = np.array([0, 0, 0])


# Calculate the coordinates of the hexagon vertices
h_v = np.array([center + radius * np.array([np.cos(2 * np.pi * k / 6), np.sin(2 * np.pi * k / 6), offset + np.random.random()]) for k in range(6)])

center = center +  np.array([0, 0, np.mean(h_v[:,2])])

# Include the center as a vertex
h_v = np.vstack((center, h_v)) 

# Define the face list with triangle indices
h_f = np.vstack((np.array([[i, (i + 1)%7, 0] for i in range(1, 6)]), np.array([6,1,0])))

h_n = igl.per_vertex_normals(h_v, h_f)

_, _, k1, k2 = igl.principal_curvature(h_v, h_f)


H = (0.5 + 0.02*np.random.rand(len(h_v)))*0.5

r = 1/H 


mesh = Mesh()
mesh.make_mesh(h_v, h_f)

v_f_adj = mesh.vertex_face_adjacency_list()

e, av_n, mid, bary_mid, r = initialize_Line_Congruence(h_v, h_f, v_f_adj, h_n, H )

ps.init()
ps.remove_all_structures()

bary_rad = np.mean(r[h_f], axis=1)

face_normals = unit(np.cross(h_v[h_f[:,1]] - h_v[h_f[:,0]], h_v[h_f[:,2]] - h_v[h_f[:,0]]))
bary = np.mean(h_v[h_f], axis=1)

c_sph_c = bary + bary_rad[:,None]*face_normals
c_sph_r = bary_rad

for i in range(len(c_sph_c)):
    sphere = ps.register_point_cloud(f"sphere_{i}", np.array([c_sph_c[i]]), enabled=True, color=(0,0,0), transparency=0.5)
    sphere.set_radius(c_sph_r[i], relative=False)



hexmesh = ps.register_surface_mesh("hexagon", h_v, h_f)
mid_mesh = ps.register_surface_mesh("Mid", np.array(mid), h_f)

hex2_mesh = ps.register_surface_mesh("hexagon 2", h_v + e, h_f)

hexmesh.add_vector_quantity("e", e, vectortype="ambient", enabled=True, color=(0,0,0))

#hexmesh.add_vector_quantity("Normals", h_n, enabled=True, color=(0,0,0))

ps.show()

Mesh Data Structure: |V| = 7, |F| = 6, |E| = 12
av_n : [[-0.0618925   0.0400538   0.9972788 ]
 [ 0.04773787 -0.10761349  0.99304604]
 [-0.11957201 -0.13744105  0.98326624]
 [-0.2333043  -0.00924098  0.97235987]
 [-0.18207236  0.15725347  0.97062918]
 [ 0.00157118  0.1965342   0.98049571]
 [ 0.11406626  0.05571342  0.99190973]]
v_ref : [[-0.47844835  0.30962842 10.70979293]
 [ 2.37215496 -0.83893342 10.64596138]
 [ 0.07116844  0.66441311 11.00220979]
 [-2.82165445  1.65989668 10.36928703]
 [-3.42796768  1.2333167  10.23785947]
 [-0.9877978  -0.20571137 10.96410034]
 [ 1.90603144 -1.28951761 10.86157137]]


In [19]:
test = np.array([[0.77775115,  0.58947903,  0.21821464],[ 0.74895543, -0.50886431,  0.42440885]])

print(np.mean(test, axis=1))
print(np.mean(test, axis=0))


[0.52848161 0.22149999]
[0.76335329 0.04030736 0.32131174]


In [15]:
import os 
import sys

# Add hananLab to path
#path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(os.getcwd()))))
path = os.path.dirname(os.getcwd())
sys.path.append(path)

import igl
import polyscope as ps
import numpy as np
import meshplot as mp


from hanan.geometry.mesh import Mesh
from hanan.geometry.utils import *
from hanan.optimization.Sphericity import Sphericity
from hanan.optimization.Optimizer import Optimizer
from hanan.optimization.LineCong import LineCong
from hanan.optimization.LineCong_Fairness import LineCong_Fair
from hanan.optimization.Torsal import Torsal
from hanan.optimization.Torsal_fairness import Torsal_Fair


# Define paths
dir_path = os.getcwd()
data_path = dir_path+"/approximation/data/" # data path

# Load test mesh
v, f = igl.read_triangle_mesh(os.path.join(data_path, "static.obj"))

n = -igl.per_vertex_normals(v, f)

_, _, k1, k2 = igl.principal_curvature(v, f)


H = 0.5*(k1 + k2)

r = 1/H 

mesh = Mesh()
mesh.make_mesh(v, f)

v_f_adj = mesh.vertex_face_adjacency_list()

e, av_n, mid, bary_mid, r = initialize_Line_Congruence(v, f, v_f_adj, n, H )

ps.init()
ps.remove_all_structures()

bary_rad = np.mean(r[f], axis=1)

face_normals = unit(np.cross(v[f[:,1]] - v[f[:,0]], v[f[:,2]] - v[f[:,0]]))
bary = np.mean(v[f], axis=1)

c_sph_c = bary - bary_rad[:,None]*face_normals
c_sph_r = bary_rad

# for _ in range(10):
#     i = np.random.randint(0, len(f))
#     sphere = ps.register_point_cloud(f"sphere_{i}", np.array([c_sph_c[i]]), enabled=True, color=(0,0,0), transparency=0.5)
#     sphere.set_radius(c_sph_r[i], relative=False)



hexmesh = ps.register_surface_mesh("hexagon", v, f)
mid_mesh = ps.register_surface_mesh("Mid", np.array(mid), f)
hexmesh. add_scalar_quantity("H", H, enabled=True, cmap="coolwarm")
hex2_mesh = ps.register_surface_mesh("hexagon 2", v + e, f)
hexmesh.add_vector_quantity("e", e, vectortype="ambient", enabled=True, color=(0,0,0))

ps.show()



Mesh Data Structure: |V| = 309, |F| = 576, |E| = 884
av_n : [[ 0.07347309  0.19802313  0.97743979]
 [ 0.9001209   0.43336001  0.04451375]
 [ 0.46336373  0.65623288  0.59552704]
 [ 0.20852618  0.9555884   0.20824897]
 [-0.21572602 -0.19706273  0.95636215]
 [ 0.76683298 -0.47412835  0.43263088]
 [ 0.58976169 -0.71316255  0.37891994]
 [ 0.72991116 -0.25376552  0.63469108]
 [-0.29574875  0.94981008 -0.10194844]
 [ 0.38945691 -0.76744072 -0.50927208]
 [-0.46543022 -0.88055392 -0.0894399 ]
 [-0.47197423 -0.87998285 -0.05357723]
 [ 0.77592579 -0.53740891  0.33034957]
 [ 0.49068264  0.6042282   0.62780477]
 [-0.76461551 -0.49229157  0.41594726]
 [-0.36406538 -0.85778915  0.3628418 ]
 [ 0.58559702 -0.25361486  0.76990625]
 [ 0.43031798 -0.5079135   0.74622403]
 [ 0.67643696  0.00474     0.73648528]
 [ 0.68950643  0.20486329  0.69470276]
 [ 0.44932747 -0.72441075  0.52281343]
 [ 0.79307281 -0.11508869  0.5981556 ]
 [ 0.13726307 -0.81062368  0.56925222]
 [ 0.29538353 -0.81980797  0.49057463]
 [-0

: 

In [12]:
import os 
import sys

# Add hananLab to path
#path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(os.getcwd()))))
path = os.path.dirname(os.getcwd())
sys.path.append(path)

import igl
import polyscope as ps
import numpy as np
import meshplot as mp
from scipy.optimize import least_squares


from hanan.geometry.mesh import Mesh
from hanan.geometry.utils import *

# Define the vertices of the 3D polygonal face (replace with your actual coordinates)
vertices = np.array([
    [0, 0, 0],
    [1, 0, 0],
    [1, 1, 0],
    [0.5, 1.5, 0],
    [0, 1, 0],
    [-0.5, 0.5, 0]
])

# Add noice to the third coordinate of the vertices
vertices[:, 2] +=  1.2*np.random.rand(len(vertices))

# Compute the centroid of the polygonal face
centroid = np.mean(vertices, axis=0)

# Compute the vectors representing the edges of the polygonal face
edges = unit(np.diff(np.vstack((vertices, centroid)), axis=0))

print("edges: ", edges)

ei = np.array([0, 1, 2, 3, 4, 5])
ej = np.array([1, 2, 3, 4, 5, 0])



# Compute the normal vector of the polygonal face
normal_vector = np.mean(np.cross(edges[ei], edges[ej]), axis=0)

# Normalize the normal vector
normal_vector /= np.linalg.norm(normal_vector)

print("dot product with each edge: ", np.sum(edges* normal_vector, axis=1)@np.sum(edges* normal_vector, axis=1))

# Find the direction vector most orthogonal to the normal vector
#direction_vector = np.array([1, 0, 0])  # Initial direction vector (replace if needed)
#most_orthogonal_direction = np.cross(normal_vector, direction_vector)

# Normalize the result
#most_orthogonal_direction /= np.linalg.norm(most_orthogonal_direction)

def edge_orth(X, edges):
    """ We want to minimize the dot product of the edges with the normal vector
    """
    return (vec_dot(edges, X))**2 + (vec_dot(X,X) - 1)**2

opt = least_squares(edge_orth, normal_vector, args=([edges]))


new_norm =  opt.x



print("new norm: ", new_norm)
print("|opt|", np.linalg.norm(new_norm))
print("dot product optimal sol: ", np.sum(edges* new_norm, axis=1)@np.sum(edges* new_norm, axis=1))

ps.init()
ps.remove_all_structures()

# Register the polygonal face
ps.register_surface_mesh("polygonal_face", vertices, [[0, 1, 2, 3, 4, 5]])

# Register the centroid
centroid = ps.register_point_cloud("centroid", np.array([centroid]), color=(0, 0, 0))

# Register the normal vector
centroid.add_vector_quantity("normal_vector", np.array([normal_vector]), color=(1, 0, 0))
centroid.add_vector_quantity("new_normal_vector", np.array([new_norm]), color=(0, 1, 0))


ps.show()

edges:  [[ 0.99950706  0.         -0.03139476]
 [ 0.          0.99811294  0.06140492]
 [-0.70335566  0.70335566  0.10286707]
 [-0.55636419 -0.55636419  0.61718536]
 [-0.67190666 -0.67190666 -0.31158125]
 [ 0.94697981  0.18939596 -0.25953498]]
dot product with each edge:  0.7517512125876855
new norm:  [ 0.30320667 -0.10760467  0.90242498]
|opt| 0.9580625746479633
dot product optimal sol:  0.48876776795757465


: 