In [1]:
import igl
import meshplot as mp
import vedo as vd
import numpy as np
import os 
from geometry.mesh import Mesh
from geometry.utils import *
from optimization.Planarity import Planarity
from optimization.Optimizer import Optimizer
from optimization.LineCong import LineCong

vd.settings.default_backend = 'k3d'

## Initial Line Congruence test

### Visualization setup

In [13]:
dir_path = os.getcwd()

data_path = dir_path+"/approximation/data/"

mv, mf = igl.read_triangle_mesh(os.path.join(data_path,"centers.obj" ))
tv, tf = igl.read_triangle_mesh(os.path.join(data_path,"test_remeshed.obj" ))
# Get vertex normals for test mesh
tn = igl.per_vertex_normals(tv, tf)

signs = np.sign(np.sum(tn * ([0,0,1]), axis=1))

# Fix normal directions
tn = tn * signs[:, None]

# Compute circumcenters and axis vectors for each triangle
p1, p2, p3 = tv[tf[:, 0]], tv[tf[:, 1]], tv[tf[:, 2]]

ct, rt, nt = circle_3pts(p1, p2, p3)

# Create dual mesh
mesh = Mesh()

mesh.make_mesh(tv,tf)

# Get inner vertices
inner_vertices = mesh.inner_vertices()

# Dual topology including outer faces
dual = mesh.dual_top()

# Dual topology without outer faces
dual_faces = [dual[vertex] for vertex in inner_vertices ]


# dual_faces = dualmesh.faces()
# # Draw vertex normals
# # vd.show(vd.Points(tv, c='red'), vd.Arrows(tv, tv + tn * 0.1, c='blue'))

# # Draw circles
# #circles = [ vd.Line(vd.Circle(ct, rt, c='k').orientation(nt), closed=True, lw=1.2, c='black') for ct, rt, nt in zip(ct, rt, nt) ]

mesh =  vd.Mesh((tv, tf), alpha = 0.8)
center = vd.Mesh((mv, mf), alpha = 0.9, c=[0.4, 0.4, 0.81])


# Create hexagonal mesh                            
h_pts = np.empty((len(tf), 3), dtype=np.float64)

# Intersect circumcircle axis with center mesh
for i in range(len(tf)):
    # Get points on circumcircle axis
    p0  = ct[i] - 10*nt[i]
    p1  = ct[i] + 10*nt[i]
    
    # Get intersection points
    h_pts[i,:] = np.array(center.intersect_with_line(p0, p1)[0])

# Create hexagonal mesh
hexmesh = vd.Mesh((h_pts, dual_faces), alpha = 0.5, c=[0.2, 0.4, 0.21])

# Draw hexagonal mesh
linesHex = []

for face in dual_faces:
        hex_face = []
        for vi in face:
            hex_face.append(h_pts[vi])
        linesHex.append(vd.Line(hex_face, closed=True, lw=1.8, c='white'))
            
# Draw edges center mesh
center_edges = center.clone().wireframe().lw(1.5).flat().c('black').alpha(1)

# Draw edges Triangular mesh
edges = mesh.clone().lw(1.5).wireframe().flat().c('k').alpha(0.5)

# Draw axis lines
# Lines vd.Lines(ct- 5*nt, ct + 5*nt, c='red', lw=0.1)
clines = vd.Lines(ct[:5]- 5*nt[:5], ct[:5] + 5*nt[:5], c='tomato', lw=0.1)

vd.show(vd.Points(tv, c='red'), mesh, center, vd.Points(h_pts, c='red'), linesHex, edges, clines)
 

/Users/cisneras/hanan/hananLab/hJupyter
/Users/cisneras/hanan/hananLab/hJupyter/approximation/data/
Mesh Data Structure: |V| = 276, |F| = 493, |E| = 768


Plot(antialias=True, axes=['x', 'y', 'z'], axes_helper=1.0, axes_helper_colors=[16711680, 65280, 255], backgro…

### Optimization setup

In [3]:
# Define paths
dir_path = os.getcwd()
data_path = dir_path+"/approximation/data/" # data path
out_path = dir_path+"/outputs/" # output path

# Load M mesh (centers of sphere mesh)
mv, mf = igl.read_triangle_mesh( os.path.join(data_path ,"centers.obj") ) 
center = vd.Mesh((mv, mf), alpha = 0.9, c=[0.4, 0.4, 0.81])
for k in range(2,3):
    tv, tf = igl.read_triangle_mesh(os.path.join(data_path,  "test_remeshed_"+str(k)+".obj"))

    # Create dual mesh
    tmesh = Mesh()

    tmesh.make_mesh(tv,tf)

    # Get vertex normals for test mesh
    e_i = igl.per_vertex_normals(tv, tf)

    signs = np.sign(np.sum(e_i * ([0,0,1]), axis=1))

    # Fix normal directions
    e_i = e_i * signs[:, None]

    # Compute circumcenters and axis vectors for each triangle
    p1, p2, p3 = tv[tf[:, 0]], tv[tf[:, 1]], tv[tf[:, 2]]

    ct, rt, nt = circle_3pts(p1, p2, p3)

    # Dual topology 
    dual = tmesh.dual_top()

    # Get inner vertices
    inner_vertices = tmesh.inner_vertices()

    # Get outer vertices
    outer_vertices = tmesh.boundary_vertices()

    # Dual topology without outer faces
    dual_faces = [dual[vertex] for vertex in inner_vertices ]

    # Create hexagonal mesh                            
    h_pts = np.empty((len(tf), 3), dtype=np.float64)

    # Intersect circumcircle axis with center mesh
    for i in range(len(tf)):
        # Get points on circumcircle axis
        p0  = ct[i] - 10*nt[i]
        p1  = ct[i] + 10*nt[i]
        
        # Get intersection points
        h_pts[i,:] = np.array(center.intersect_with_line(p0, p1)[0])

    # Create hexagonal mesh
    # hexmesh = vd.Mesh((h_pts, dual_faces), alpha = 0.5, c=[0.2, 0.4, 0.21])

    # # Draw hexagonal mesh
    # linesHex = []

    # for face in dual_faces:
    #         hex_face = []
    #         for vi in face:
    #             hex_face.append(h_pts[vi])
    #         linesHex.append(vd.Line(hex_face, closed=True, lw=1.8, c='white'))


    # Init e_i vectors
    # # Variables  are X = [e_i]
    X = e_i.flatten()

    # # Init constraints
    linecong = LineCong()
    linecong.initialize_constraint(h_pts, dual_faces, e_i.shape[0], X)


    # # init optimizer
    opt = Optimizer()

    opt.initialize_optimizer(X)


    for i in range(20):

        # Compute J, r for each constraint
        linecong.compute(h_pts, dual_faces, X)
        
        # Add constraints  
        opt.add_constraint(linecong)

        # Fix vertices
        #opt.fix_vertices(outer_vertices)

        # Optimize
        opt.optimize("LM")


    e_i = opt.X.reshape(-1,3)   
        
    file_pts = open(os.path.join( out_path, "points_"+str(k)+".dat"), "w")
    directions = open(os.path.join( out_path, "directions_"+str(k)+".dat"), "w")
    for v  in tmesh.inner_vertices():
        file_pts.write(str(tmesh.vertices[v][0]) + " " + str(tmesh.vertices[v][1]) + " " + str(tmesh.vertices[v][2]) + "\n")
        directions.write(str(e_i[v][0]) + " " + str(e_i[v][1]) + " " + str(e_i[v][2]) + "\n")

    file_pts.close()
    directions.close()


Mesh Data Structure: |V| = 469, |F| = 858, |E| = 1326


### Visual Verification

In [6]:
# Define paths
dir_path = os.getcwd()
data_path = dir_path+"/approximation/data/" # data path
out_path = dir_path+"/outputs/" # output path



# Load M mesh (centers of sphere mesh)
mv, mf = igl.read_triangle_mesh( os.path.join(data_path ,"centers.obj") ) 
center = vd.Mesh((mv, mf), alpha = 0.9, c=[0.4, 0.4, 0.81])

# Data of interest
k = 2

tv, tf = igl.read_triangle_mesh(os.path.join(data_path,  "test_remeshed_"+str(k)+".obj"))

test_mesh =  vd.Mesh((tv, tf), alpha = 0.8)
# Draw edges Triangular mesh
edges = test_mesh.clone().lw(1.5).wireframe().flat().c('k').alpha(0.5)

# Create dual mesh
tmesh = Mesh()
tmesh.make_mesh(tv,tf)

# Get vertex normals for test mesh
e_i = igl.per_vertex_normals(tv, tf)

signs = np.sign(np.sum(e_i * ([0,0,1]), axis=1))

# Fix normal directions
e_i = e_i * signs[:, None]



# Data files
file_pts = open(os.path.join( out_path, "points_"+str(k)+".dat"), "w")
ref = open(os.path.join( out_path, "init_directions_"+str(k)+".dat"), "w")
for v  in tmesh.inner_vertices():
    file_pts.write(str(tmesh.vertices[v][0]) + " " + str(tmesh.vertices[v][1]) + " " + str(tmesh.vertices[v][2]) + "\n")
    ref.write(str(e_i[v][0]) + " " + str(e_i[v][1]) + " " + str(e_i[v][2]) + "\n")

file_pts.close()
ref.close()



# Compute circumcenters and axis vectors for each triangle
p1, p2, p3 = tv[tf[:, 0]], tv[tf[:, 1]], tv[tf[:, 2]]

ct, rt, nt = circle_3pts(p1, p2, p3)

# Dual topology 
dual = tmesh.dual_top()

# Get inner vertices
inner_vertices = tmesh.inner_vertices()

# Get outer vertices
outer_vertices = tmesh.boundary_vertices()

# Dual topology without outer faces
dual_faces = [dual[vertex] for vertex in inner_vertices ]

# Create hexagonal mesh                            
h_pts = np.empty((len(tf), 3), dtype=np.float64)

# Intersect circumcircle axis with center mesh
for i in range(len(tf)):
    # Get points on circumcircle axis
    p0  = ct[i] - 10*nt[i]
    p1  = ct[i] + 10*nt[i]
    
    # Get intersection points
    h_pts[i,:] = np.array(center.intersect_with_line(p0, p1)[0])

# Create hexagonal mesh
# hexmesh = vd.Mesh((h_pts, dual_faces), alpha = 0.5, c=[0.2, 0.4, 0.21])

# # Draw hexagonal mesh
linesHex = []

for face in dual_faces:
        hex_face = []
        for vi in face:
            hex_face.append(h_pts[vi])
        linesHex.append(vd.Line(hex_face, closed=True, lw=1.8, c='white'))


# Init e_i vectors
# # Variables  are X = [e_i]
X = e_i[inner_vertices].flatten()

# # Init constraints
linecong = LineCong()
linecong.initialize_constraint(h_pts, dual_faces, len(inner_vertices), X)


# # init optimizer
opt = Optimizer()

opt.initialize_optimizer(X)


for i in range(10):
    directions = open(os.path.join( out_path, "directions_"+str(k)+"_"+str(i)+".dat"), "w")

    # Compute J, r for each constraint
    linecong.compute(h_pts, dual_faces, X)
    
    # Add constraints  
    opt.add_constraint(linecong)

    # Fix vertices
    #opt.fix_vertices(outer_vertices)

    # Optimize
    opt.optimize("LM")

    e_i = opt.X.reshape(-1,3)   

    for v  in range(len(tmesh.inner_vertices())):
    
        directions.write(str(e_i[v][0]) + " " + str(e_i[v][1]) + " " + str(e_i[v][2]) + "\n")

    directions.close()

opt.print_log()
e_i = opt.X.reshape(-1,3)   


#test_mesh =  vd.Mesh((tv, tf), alpha = 0.8)

congruence = vd.Lines(tv[0:1]- 5*e_i[0:1], tv[0:1] + 5*e_i[0:1], c=[0.8,0.5,0.5], lw=0.1)

# # Draw hexagonal mesh
linesHex = []

for face in [dual_faces[0]]:
        hex_face = []
        for vi in face:
            hex_face.append(h_pts[vi])
        linesHex.append(vd.Line(hex_face, closed=True, lw=1.8, c='white'))

for vi in range(len(h_pts[dual_faces[0]])):

    v0 = h_pts[dual_faces[0]][vi]
    v1 = h_pts[dual_faces[0]][(vi+1)%len(h_pts[dual_faces[0]])]
    edge = (v1 - v0) / np.linalg.norm(v1 - v0)
    #print(edge@e_i[0])
    #print(linecong.cij[vi]@e_i[0])

print(linecong.J.shape)

# # Show the scene
# plotter.show()
#vd.show(vd.Points(tv, c='red'), test_mesh, center, vd.Points(h_pts, c='red'), linesHex, edges, congruence)

Mesh Data Structure: |V| = 469, |F| = 858, |E| = 1326
ei : 391
cf : 391
      Energy
0  78.036198
1  13.150906
2   2.373584
3   0.698637
4   0.430570
5   0.387579
6   0.380713
7   0.379609
8   0.379433
9   0.379404
(3514, 1173)


### Save Results

In [6]:
flnum = 2
file_pts = open("/home/anthony/Hanan Lab/hananLab/hJupyter/outputs/points_"+str(flnum)+".dat", "w")
directions = open("/home/anthony/Hanan Lab/hananLab/hJupyter/outputs/directions_"+str(flnum)+".dat", "w")
for v  in tmesh.inner_vertices():
    file_pts.write(str(tmesh.vertices[v][0]) + " " + str(tmesh.vertices[v][1]) + " " + str(tmesh.vertices[v][2]) + "\n")
    directions.write(str(e_i[v][0]) + " " + str(e_i[v][1]) + " " + str(e_i[v][2]) + "\n")

file_pts.close()
directions.close()
    

In [2]:
clines = vd.Lines(tv[:50]- 5*e_i[:50], tv[:50] + 5*e_i[:50], c='tomato', lw=0.1)

vd.show(vd.Points(tv, c='red'), mesh, center, vd.Points(h_pts, c='red'), linesHex, edges, clines)

NameError: name 'tv' is not defined

In [23]:
"""Add a square button with N possible internal states
to a rendering window that calls an external function"""
from vedo import Plotter, Mesh, dataurl, printc

# Define a function that toggles the transparency of a mesh
#  and changes the button state
def buttonfunc(evt):
    if evt.actor and evt.actor.name == "mybutton":
        mesh.alpha(1 - mesh.alpha())  # toggle mesh transparency
        bu.switch()                   # change to next status
        printc(bu.status(), box="_", dim=True)

# Load a mesh and set its color to violet
mesh = Mesh(dataurl+"magnolia.vtk").c("violet").flat()

# Create an instance of the Plotter class with axes style-11 enabled
plt = Plotter(axes=11)

# Add a button to the plotter with buttonfunc as the callback function
bu = plt.add_button(
    buttonfunc,
    pos=(0.7, 0.05),  # x,y fraction from bottom left corner
    states=["click to hide", "click to show"],  # text for each state
    c=["w", "w"],     # font color for each state
    bc=["dg", "dv"],  # background color for each state
    font="courier",   # font type
    size=25,          # font size
    bold=True,        # bold font
    italic=False     # non-italic font style
)

# Show the mesh, docstring, and button in the plot
plt.show(mesh, __doc__).close()

AttributeError: 'NoneType' object has no attribute 'AddActor2D'

### Test Circumcircle

In [18]:

# Get a list of random points
#p = np.random.rand(10,3)

p1 = np.random.rand(10,3)
p2 = np.random.rand(10,3)
p3 = np.random.rand(10,3)

c, rad, n = circle_3pts(p1,p2,p3)
print(f"centers: {c}\t rad: {rad}\t n: {n}")
circles = []
for ci in range(len(c)):
    print(f"centers: {c[ci]}\t rad: {rad[ci]}\t n: {n[ci]}")
    if ci%2 == 0:
        circles.append( vd.Circle(c[ci], r=rad[ci], c='red', alpha = 0.5).orientation(n[ci])) 
    else:
        circles.append( vd.Circle(c[ci], r=rad[ci], c="green", alpha = 0.5).orientation(n[ci])) 
pts1 = vd.Points(np.array( np.vstack((p1, p2, p3))), r = 10, c = 'black')
#pts2 = vd.Points(np.array([p1[1], p2[1], p3[1]]), r = 10, c = 'green')

vd.show(pts1,*circles)


centers: [[0.38706174 0.18167749 0.42761195]
 [0.36449233 0.53954026 0.53625345]
 [0.4790021  0.50663046 0.53923755]
 [0.72571721 0.38713089 0.48248336]
 [0.25824261 0.47411309 0.44878618]
 [0.33559659 0.53053444 0.78727609]
 [0.37826845 0.85980277 0.14845869]
 [0.43063887 0.91308919 0.36782106]
 [0.46524639 0.38363435 0.63320613]
 [0.76475174 0.3663979  0.58271725]]	 rad: [0.53952315 0.56166778 0.6054543  0.57289953 0.44627465 0.28358589
 0.43692063 0.51683852 0.5218032  0.35828794]	 n: [[-0.69549541 -0.29458511  0.65536688]
 [ 0.89194074  0.14805501 -0.42722527]
 [ 0.63249859  0.58508785 -0.50756059]
 [-0.10723602  0.63963098  0.76116532]
 [ 0.95015298 -0.29102825 -0.11185647]
 [ 0.69205191  0.40075536 -0.60038263]
 [ 0.06192396 -0.85263981 -0.51881671]
 [ 0.64050028  0.31389121 -0.70087923]
 [-0.72805365 -0.09385479  0.67906491]
 [-0.43649262 -0.83909511  0.32464379]]
centers: [0.38706174 0.18167749 0.42761195]	 rad: 0.5395231503681077	 n: [-0.69549541 -0.29458511  0.65536688]
cente

Plot(antialias=True, axes=['x', 'y', 'z'], axes_helper=1.0, axes_helper_colors=[16711680, 65280, 255], backgro…

## Sample Planarity Opt

In [2]:
# Create four quads in 3D that merge in a vertex
v = np.array(
    [
        [ 0.01,  0.01,  0.8],
        [ 1.01,  0.03,  0.01],
        [-1.02,  0.02,  0.01],
        [ 0.01,  1.1, -0.2],
        [ 0.01, -1.3, -0.3],
        [-1.02,  1.01,  0.1],
        [ 1.01,  1.02,  0.2],
        [-1.04, -1.03, -0.3],
        [ 1.05, -1.04,  0.1],
    ]
   )
fcs = np.array([[0, 1, 6, 3], [2, 0, 3, 5], [7, 4, 0, 2], [4, 8, 1, 0]])

# Make mesh
m = Mesh()
m.make_mesh(v, fcs)

mesh1 = vd.Mesh((v, fcs), alpha = 0.8, c='r')

X = np.zeros((3*m.V+3*m.F), dtype=np.float64)

X[:3*m.V] = m.vertices.flatten()

# Init constraints
planarity = Planarity()
planarity.initialize_constraint(m, X)


# init optimizer
opt = Optimizer()

opt.initialize_optimizer(X)

for i in range(10):

    # Compute J, r for each constraint
    planarity.compute(m, X)
    
    # Add constraints  
    opt.add_constraint(planarity)
    opt.optimize("LM")
 

mesh2 = vd.Mesh((opt.X[:3*m.V].reshape(m.V,3),  fcs), alpha = 0.9, c='b')

print(opt.energy)

vd.show(mesh1, mesh2)



Mesh Data Structure: |V| = 9, |F| = 4, |E| = 12
[171.85628720367802, 2.036814821305436, 0.4337323303603914, 0.07705210210478547, 0.031784467050821524, 0.009450738303690037, 0.0037967153241723027, 0.0012778421481861343, 0.0004787422283860423, 0.0001682370848148311]


Plot(antialias=True, axes=['x', 'y', 'z'], axes_helper=1.0, axes_helper_colors=[16711680, 65280, 255], backgro…

In [ ]:
# Create four quads in 3D that merge in a vertex
v = np.array(
    [
        [ 0.01,  0.01,  0.8],
        [ 1.01,  0.03,  0.01],
        [-1.02,  0.02,  0.01],
        [ 0.01,  1.1, -0.2],
        [ 0.01, -1.3, -0.3],
        [-1.02,  1.01,  0.1],
        [ 1.01,  1.02,  0.2],
        [-1.04, -1.03, -0.3],
        [ 1.05, -1.04,  0.1],
    ]
   )
fcs = np.array([[0, 1, 6, 3], [2, 0, 3, 5], [7, 4, 0, 2], [4, 8, 1, 0]])

new_v = v.copy()


# Make mesh
m = mesh.Mesh()
m.make_mesh(v, fcs)

#print(f"V before:\n{v}")

# Planarity
# Constraint  n . (vi - vj) per each edge (vi, vj) in F, so we have 4 constraints per each face
# Our variables are the vertices of the mesh, so we have 3n variables plus the auxiliary variable
# n the normals of the faces which result in 3*n + 3*F variables
H = np.zeros((m.F*5, m.V*3+ 3*m.F), dtype=np.float64)

b = np.zeros(m.F*5, dtype=np.float64)

# Fill H

# Compute initial auxiliary variable


# Get list of indices 
iv0, iv1, iv2, iv3 = m.faces()[:,0], m.faces()[:,1], m.faces()[:,2], m.faces()[:,3]

# v0, v1, v2, v3 = v[iv0], v[iv1], v[iv2], v[iv3]
diag1 = v[iv2] - v[iv0]
diag2 = v[iv3] - v[iv1]

# # Compute normals
normals = np.cross(diag1, diag2)

#normals = np.repeat([0,0,1], m.F).reshape(m.F, 3)
#l_normals = np.linalg.norm(normals, axis=1)

#normals =np.ones((m.F, 3))

# Variables will be in the form X = [ vix
#                                     viy
#                                     viz
#                                     nix
#                                     niy
#                                     niz]



it = 10

# First Edge Constraint ni . (v1 - v0) = 0 
for i in range(it):
    H = np.zeros((m.F*5, m.V*3+ 3*m.F), dtype=np.float64)
    # # X
    # H[:m.F, 3*iv0] = - normals[:,0]
    # H[:m.F, 3*iv1] =   normals[:,0]
    # # Y
    # H[:m.F, 3*iv0+1] = - normals[:,1]
    # H[:m.F, 3*iv1+1] =   normals[:,1]
    # # Z 
    # H[:m.F, 3*iv0+2] = - normals[:,2]
    # H[:m.F, 3*iv1+2] =   normals[:,2]

    # # Second Edge Constraint ni . (v2 - v1) = 0

    # # X
    # H[m.F:2*m.F, 3*iv1] = - normals[:,0]
    # H[m.F:2*m.F, 3*iv2] =   normals[:,0]
    # # Y
    # H[m.F:2*m.F, 3*iv1+1] = - normals[:,1]
    # H[m.F:2*m.F, 3*iv2+1] =   normals[:,1]
    # # Z
    # H[m.F:2*m.F, 3*iv1+2] = - normals[:,2]
    # H[m.F:2*m.F, 3*iv2+2] =   normals[:,2]

    # # Third Edge Constraint ni . (v3 - v2) = 0

    # # X
    # H[2*m.F:3*m.F, 3*iv2] = - normals[:,0]
    # H[2*m.F:3*m.F, 3*iv3] =   normals[:,0]
    # # Y
    # H[2*m.F:3*m.F, 3*iv2+1] = - normals[:,1]
    # H[2*m.F:3*m.F, 3*iv3+1] =   normals[:,1]
    # # Z
    # H[2*m.F:3*m.F, 3*iv2+2] = - normals[:,2]
    # H[2*m.F:3*m.F, 3*iv3+2] =   normals[:,2]

    # # Fourth Edge Constraint ni . (v0 - v3) = 0

    # # X
    # H[3*m.F:4*m.F, 3*iv3] = - normals[:,0]
    # H[3*m.F:4*m.F, 3*iv0] =   normals[:,0]
    # # Y
    # H[3*m.F:4*m.F, 3*iv3+1] = - normals[:,1]
    # H[3*m.F:4*m.F, 3*iv0+1] =   normals[:,1]
    # # Z
    # H[3*m.F:4*m.F, 3*iv3+2] = - normals[:,2]
    # H[3*m.F:4*m.F, 3*iv0+2] =   normals[:,2]

    # Compute initial auxiliary variable 

    # Compute sums of vertices diferences
    #face_edge_sum = (v1-v0) + (v2-v1) + (v3-v2) + (v0-v3)
    for f in range(m.F):

        iv0, iv1, iv2, iv3 = m.faces()[f]    

        v0, v1, v2, v3 = new_v[iv0], new_v[iv1], new_v[iv2], new_v[iv3]

        # Edge constraint nf(v1 - v0) = 0
        H[        f, 3*iv0: 3*iv0 + 3] = - normals[f]
        H[        f, 3*iv1: 3*iv1 + 3] =   normals[f]

        # Edge constraint nf(v2 - v1) = 0
        H[  m.F + f, 3*iv1: 3*iv1 + 3] = - normals[f]
        H[  m.F + f, 3*iv2: 3*iv2 + 3] =   normals[f]

        # Edge constraint nf(v3 - v2) = 0
        H[2*m.F + f, 3*iv2: 3*iv2 + 3] = - normals[f]
        H[2*m.F + f, 3*iv3: 3*iv3 + 3] =   normals[f]

        # Edge constraint nf(v0 - v3) = 0
        H[3*m.F + f, 3*iv3: 3*iv3 + 3] = - normals[f]
        H[3*m.F + f, 3*iv0: 3*iv0 + 3] =   normals[f]

        # Edge constraint nf(vi - vj) = 0 normal derivative
        H[        f, 3*m.V + 3*f: 3*m.V + 3*f+3] = (v1 - v0)
        H[  m.F + f, 3*m.V + 3*f: 3*m.V + 3*f+3] = (v2 - v1)
        H[2*m.F + f, 3*m.V + 3*f: 3*m.V + 3*f+3] = (v3 - v2)
        H[3*m.F + f, 3*m.V + 3*f: 3*m.V + 3*f+3] = (v0 - v3)

    
        b[        f] = np.dot(normals[f], v1 - v0)
        b[  m.F + f] = np.dot(normals[f], v2 - v1)
        b[2*m.F + f] = np.dot(normals[f], v3 - v2)
        b[3*m.F + f] = np.dot(normals[f], v0 - v3)

        # Unit normal constraint
        H[4*m.F + f, 3*m.V + 3*f: 3*m.V + 3*f+3] = normals[f]
        b[4*m.F + f] = normals[f]@normals[f] - 1


    hess = H.T @ H
    grad = - H.T @ b


    #print(f"normals norms: {np.linalg.norm(normals, axis=1)}")

    print(f"energy: {b @ b}")
    #print(f"Hess: {hess}")
    #print(f"Grad: {grad}")

    diag_H = max(np.diag(hess))
    #print(f"diag_H: {diag_H}")
    hess += np.eye(hess.shape[0]) * 1e-6 * diag_H

    # Solve
    delta = np.linalg.solve(hess, grad)

    step = 0.8

    new_v = new_v + step*delta[:3*m.V].reshape(m.V, 3)
    normals = normals + step*delta[3*m.V:].reshape(m.F, 3)

#print(f"delta:\n{delta[:3*m.V]}")
#print(f"delta:\n{delta[:3*m.V].reshape(m.V, 3)}")
#print(f"v after:\n{v}")
#print(f"v opt:\n{new_v}")

normals_draw = []
# Draw normals
for i in range(m.F):
    iv0, iv1, iv2, iv3 = m.faces()[i]    
    # Compute baricenter
    baricenter = (new_v[iv0] + new_v[iv1] + new_v[iv2] + new_v[iv3])/4
    # Draw normal
    norm_arrow = vd.Arrow(baricenter, baricenter + normals[i], c='g')
    normals_draw.append(norm_arrow)

mesh1 = vd.Mesh((v, fcs), alpha = 0.8, c='r')
mesh2 = vd.Mesh((new_v, fcs), alpha = 0.9, c='b')

print(new_v)
vd.show(mesh1, mesh2)


Mesh Data Structure: |V| = 9, |F| = 4, |E| = 12
energy: 171.85628720367802
energy: 2.03681482140429
energy: 0.43373233036153064
energy: 0.07705210210474875
energy: 0.031784467050890546
energy: 0.009450738303705323
energy: 0.0037967153241796675
energy: 0.0012778421481883686
energy: 0.00047874222838693555
energy: 0.0001682370848151371
[[-0.0282462  -0.03527448  0.54050374]
 [ 1.08241622  0.02345078  0.32472876]
 [-1.07104158  0.09778534  0.20540845]
 [ 0.01338739  1.20236083  0.04901083]
 [ 0.05172566 -1.37693558 -0.12078301]
 [-0.96808993  0.92290748 -0.1020004 ]
 [ 0.96446049  0.93589436 -0.01181976]
 [-1.02053307 -1.00480963 -0.34393629]
 [ 0.99592102 -0.9453791  -0.12111233]]


Plot(antialias=True, axes=['x', 'y', 'z'], axes_helper=1.0, axes_helper_colors=[16711680, 65280, 255], backgro…

In [ ]:
v, f = igl.read_triangle_mesh("models/catenoid_def_1.obj")
mesh = om.read_trimesh("models/catenoid_def_1.obj")
mp.plot(v, f, c=v[:, 0])

  o catenoid_def


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0485900…

In [ ]:
def iso_stereo(n, h):
    # Isotropic model stereographic projection
    # n: normal vector
    # h: distance center to plane
    # return point in I3

    # Concatenate n[1:2] and h
    return np.vstack((n[1:2],v))/(1+ n[2])

In [ ]:
a = np.array([[1, 2, 3],[5,4,2] , [9,7,2]])
b = np.array([19,22,89])
# Add b as a column to a
c = np.column_stack((a,b))
print(a[:, 0:2])

[[1 2]
 [5 4]
 [9 7]]


In [ ]:
# Get face normals
nf = igl.per_face_normals(v, f, np.array([0.0, 0.0, 0.0]))
# Get indices v1 of each face
iv1 = f[:, 0]
# Get vertices of idv1
v1 = v[iv1, :]
# Compute dot product of each face normal with v1
h = np.sum(nf * v1, axis=1)

# Get Isotropic point per face
nv = np.column_stack((nf[:, 0:2], h)) / (1 + nf[:, 2, None])

nf = np.empty((0, 3), dtype=np.int32)

for fi in range(len(f)):
    aux = np.empty((0, ), dtype=np.int32)
    for adf in mesh.ff(mesh.face_handle(fi)):
        aux = np.hstack((aux, [adf.idx()]))
    if len(aux) == 3:
        nf = np.vstack((nf, aux))

mp.plot(nv, nf[:2])




Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(1.8548016…

IndexError: list index out of range

In [8]:
from scipy.sparse.linalg import spsolve
from scipy.sparse import csr_matrix

v, f = igl.read_triangle_mesh("models/Hall.obj")

# Draw the mesh
n = igl.per_vertex_normals(v, f) * 0.5 + 0.5
c = np.linalg.norm(n, axis=1)
p = mp.plot(v, f, c, return_plot=True) # plot

# Compute Cuvature properties
v1, v2, k1, k2 = igl.principal_curvature(v, f)



# Compute focal surfaces
rho1 = 100
rho2 = 1/k2

step = 0.001

lamb = 0.1 * np.ones(v.shape[0], dtype=np.float64)

J = np.eye(v.shape[0], dtype=np.float64) 

# Precalculate intermediate states
vs = [v]
cs = [c]
for i in range(30):
    # Compute the gradient of the focal surface
    H = csr_matrix(J.T@J)
    b = - J.T@(lamb - rho1)
    delta = spsolve(H, b)
    lamb = lamb + step * delta
    # Update the mesh
    v = v + lamb[:,None]*n

    # Recompute the normals
    n = igl.per_vertex_normals(v, f) * 0.5 + 0.5
    c = np.linalg.norm(n, axis=1)
    # Add to the list
    # p.update_object(vertices=v, colors=c)
    vs.append(v)
    cs.append(c)
    

# Add interactive visulization
@mp.interact(level=(0, 9))
def mcf(level=0):
    p.update_object(vertices=vs[level], colors=cs[level])
    vs.append(v)
    cs.append(c)
p

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(19.867670…

interactive(children=(IntSlider(value=0, description='level', max=9), Output()), _dom_classes=('widget-interac…