In [1]:
import igl
#import meshplot as mp
import vedo as vd
import polyscope as ps
import numpy as np
import os 
import time 
from geometry.mesh import Mesh
from geometry.utils import *
from optimization.Planarity import Planarity
from optimization.HyperbolicLC import HyperbolicLC
from optimization.Optimizer import Optimizer
from optimization.LineCong import LineCong

vd.settings.default_backend = 'k3d'

## Initial Line Congruence test

### Visualization setup

In [ ]:
dir_path = os.getcwd()

data_path = dir_path+"/approximation/data/"

mv, mf = igl.read_triangle_mesh(os.path.join(data_path,"centers.obj" ))
tv, tf = igl.read_triangle_mesh(os.path.join(data_path,"test_remeshed.obj" ))
# Get vertex normals for test mesh
tn = igl.per_vertex_normals(tv, tf)

signs = np.sign(np.sum(tn * ([0,0,1]), axis=1))

# Fix normal directions
tn = tn * signs[:, None]

# Compute circumcenters and axis vectors for each triangle
p1, p2, p3 = tv[tf[:, 0]], tv[tf[:, 1]], tv[tf[:, 2]]

ct, rt, nt = circle_3pts(p1, p2, p3)

# Create dual mesh
mesh = Mesh()

mesh.make_mesh(tv,tf)

# Get inner vertices
inner_vertices = mesh.inner_vertices()

# Dual topology including outer faces
dual = mesh.dual_top()

# Dual topology without outer faces
dual_faces = [dual[vertex] for vertex in inner_vertices ]


# dual_faces = dualmesh.faces()
# # Draw vertex normals
# # vd.show(vd.Points(tv, c='red'), vd.Arrows(tv, tv + tn * 0.1, c='blue'))

# # Draw circles
# #circles = [ vd.Line(vd.Circle(ct, rt, c='k').orientation(nt), closed=True, lw=1.2, c='black') for ct, rt, nt in zip(ct, rt, nt) ]

# Create test mesh and center mesh 
mesh =  vd.Mesh((tv, tf), alpha = 0.8)
center = vd.Mesh((mv, mf), alpha = 0.9, c=[0.4, 0.4, 0.81])

# Create hexagonal mesh                            
h_pts = np.empty((len(tf), 3), dtype=np.float64)

# Intersect circumcircle axis with center mesh
for i in range(len(tf)):
    # Get points on circumcircle axis
    p0  = ct[i] - 10*nt[i]
    p1  = ct[i] + 10*nt[i]
    
    # Get intersection points
    h_pts[i,:] = np.array(center.intersect_with_line(p0, p1)[0])

# Create hexagonal mesh
hexmesh = vd.Mesh((h_pts, dual_faces), alpha = 0.5, c=[0.2, 0.4, 0.21])

# Draw hexagonal mesh
linesHex = []

for face in dual_faces:
        hex_face = []
        for vi in face:
            hex_face.append(h_pts[vi])
        linesHex.append(vd.Line(hex_face, closed=True, lw=1.8, c='white'))
            
# Draw edges center mesh
center_edges = center.clone().wireframe().lw(1.5).flat().c('black').alpha(1)

# Draw edges Triangular mesh
edges = mesh.clone().lw(1.5).wireframe().flat().c('k').alpha(0.5)

# Draw axis lines
# Lines vd.Lines(ct- 5*nt, ct + 5*nt, c='red', lw=0.1)
clines = vd.Lines(ct[:5]- 5*nt[:5], ct[:5] + 5*nt[:5], c='tomato', lw=0.1)

vd.show(vd.Points(tv, c='red'), mesh, center, vd.Points(h_pts, c='red'), linesHex, edges, clines)
 

### Optimization Test

In [4]:
# Define paths
dir_path = os.getcwd()
data_path = dir_path+"/approximation/data/" # data path
out_path = dir_path+"/outputs/" # output path

# Data of interest
k = 2

# Init data files
file_pts = open(os.path.join( out_path, "points_"+str(k)+".dat"), "w")
ref = open(os.path.join( out_path, "init_directions_"+str(k)+".dat"), "w")


# Load M mesh (centers of sphere mesh)
mv, mf = igl.read_triangle_mesh( os.path.join(data_path ,"centers.obj") ) 
center = vd.Mesh((mv, mf), alpha = 0.9, c=[0.4, 0.4, 0.81])


# Load test mesh
tv, tf = igl.read_triangle_mesh(os.path.join(data_path,  "test_remeshed_"+str(k)+".obj"))

# Create dual mesh
tmesh = Mesh()
tmesh.make_mesh(tv,tf)
# Get inner vertices
inner_vertices = tmesh.inner_vertices()
# Get outer vertices
outer_vertices = tmesh.boundary_vertices()

# Get vertex normals for test mesh
e_i = igl.per_vertex_normals(tv, tf)

# Fix normal directions
signs = np.sign(np.sum(e_i * ([0,0,1]), axis=1))
e_i = e_i * signs[:, None]

# Compute circumcenters and axis vectors for each triangle
p1, p2, p3 = tv[tf[:, 0]], tv[tf[:, 1]], tv[tf[:, 2]]

ct, rt, nt = circle_3pts(p1, p2, p3)

# Dual topology 
dual = tmesh.vertex_ring_faces_list()

# Dual topology without outer faces
dual_faces = [dual[vertex] for vertex in inner_vertices ]

# Create hexagonal mesh                            
h_pts = np.empty((len(tf), 3), dtype=np.float64)

# Intersect circumcircle axis with center mesh
for i in range(len(tf)):
    # Get points on circumcircle axis
    p0  = ct[i] - 10*nt[i]
    p1  = ct[i] + 10*nt[i]
    
    # Get intersection points
    h_pts[i,:] = np.array(center.intersect_with_line(p0, p1)[0])


# # Write data to file
for v  in tmesh.inner_vertices():
    file_pts.write(str(tmesh.vertices[v][0]) + " " + str(tmesh.vertices[v][1]) + " " + str(tmesh.vertices[v][2]) + "\n")
    ref.write(str(e_i[v][0]) + " " + str(e_i[v][1]) + " " + str(e_i[v][2]) + "\n")

file_pts.close()
ref.close()


# Optimization
# Init  X0 = [e_i | A| delta]
X = e_i.flatten() 

# Init constraints
linecong = LineCong()

linecong.initialize_constraint(X, len(tv), h_pts, dual, inner_vertices)
 
# Init optimizer
opt = Optimizer()
opt.initialize_optimizer(X)

for i in range(10):
    # Create file per iteration
    directions = open(os.path.join( out_path, "directions_"+str(k)+"_"+str(i)+".dat"), "w")

    # Compute J, r for each constraint
    linecong.compute(inner_vertices, dual, X)
    
    # Add constraints  
    opt.add_constraint(linecong)

    # Optimize
    opt.optimize("LM")

    e_i = opt.X.reshape(-1,3)   

    # Write data to file
    for v  in inner_vertices:   
        directions.write(str(e_i[v][0]) + " " + str(e_i[v][1]) + " " + str(e_i[v][2]) + "\n")
    directions.close()

# Print log
opt.print_log()
e_i = opt.X.reshape(-1,3)   
    
# Visualize line congruence
#congruence = vd.Lines(tv[inner_vertices[:5]]- 5*e_i[inner_vertices[:5]], tv[inner_vertices[:5]] + 5*e_i[inner_vertices[:5]], c=[0.8,0.5,0.5], lw=0.1)


Mesh Data Structure: |V| = 469, |F| = 858, |E| = 1326
      Energy
0  78.036198
1  10.887505
2   1.699542
3   0.549916
4   0.401698
5   0.382214
6   0.380081
7   0.379561
8   0.379438
9   0.379408


# Torsal test

In [14]:
def torsal_directions(v, f, e_i):
    num_faces = len(f)
    tors = np.zeros((2 * num_faces, 3))
    cos_tors = np.zeros(num_faces)
    for i in range(num_faces):
        # Extract vertex indices for the current face
        vertex_indices = f[i]

        # Calculate vectors e(u, v), e_u, e_v for the current face
        e_u, e_v = e_i[vertex_indices[1]] - e_i[vertex_indices[0]], \
                    e_i[vertex_indices[2]] - e_i[vertex_indices[0]]
        e = (e_i[vertex_indices[0]] + e_i[vertex_indices[1]] + e_i[vertex_indices[2]])/3

        # Calculate vectors a(u, v), a_u, a_v for the current face
        v_u, v_v = v[vertex_indices[1]] - v[vertex_indices[0]], \
                    v[vertex_indices[2]] - v[vertex_indices[0]]
        vv = (v[vertex_indices[0]] + v[vertex_indices[1]]+ v[vertex_indices[2]])/3

        # Calculate coefficients of the equation and solve it
        gamma_0 = np.linalg.det(np.array([e_u, v_u, e]))
        gamma_1 = np.linalg.det(np.array([e_u, v_v, e])) + np.linalg.det(np.array([e_v, v_u, e]))
        gamma_2 = np.linalg.det(np.array([e_v, v_v, e]))

        discr = gamma_1 * gamma_1 - 4.0 * gamma_0 * gamma_2
        # here should be exception about the negative discriminant
        soln = [(-gamma_1 - np.sqrt(discr)), (-gamma_1 + np.sqrt(discr))]
        sold = (2.0 * gamma_0)

        # Calculate torsal directions for the current face
        tors1 = soln[0] * v_u + sold * v_v
        tors1 = tors1 / np.linalg.norm(tors1)
        tors[2*i] = tors1
        tors2 = soln[1] * v_u + sold * v_v
        tors2 = tors2 / np.linalg.norm(tors2)
        tors[2 * i + 1] = tors2

        normal_plane_1 = np.cross(tors1, e)
        normal_plane_2 = np.cross(tors2, e)
        cos_tors[i] = abs(np.dot(normal_plane_1, normal_plane_2)) / (np.linalg.norm(normal_plane_1) * np.linalg.norm(normal_plane_2))

    return tors, cos_tors

In [9]:
def torsal_dir_vec(tv, tf, e_i):
    # Compute torsal directions 
    barycenters = np.zeros((len(tf), 3))

    # Get vertices
    vi, vj, vk = tv[tf[:,0]], tv[tf[:,1]], tv[tf[:,2]]  
    # Get directions
    ei, ej, ek = e_i[tf[:,0]], e_i[tf[:,1]], e_i[tf[:,2]]

    # Compute edges
    eij = ej - ei
    eik = ek - ei

    # Compute vectors
    vij = vj - vi
    vik = vk - vi

    # Compute barycenter of directions
    ec = np.sum( e_i[tf], axis = 1)/3

    #ec = ec/np.linalg.norm(ec)

    # Compute barycenter of vertices
    barycenters = (vi + vj+ vk)/3

    # Cross products
    vijXec = np.cross(vij, ec)
    vikXec = np.cross(vik, ec)

    # Compute coefficients
    g0 = np.sum(eij*vijXec, axis=1)
    g1 = np.sum(eij*vikXec, axis=1) + np.sum(eik*vijXec, axis=1)
    g2 = np.sum(eik*vikXec, axis=1)

    # Compute discriminant
    disc = g1**2 - 4*g0*g2
    
    negative_disc = np.where((disc < 0) & (np.abs(disc) > 1e-6))
    small_disc = np.where((disc < 0) & (np.abs(disc) < 1e-6))
    large_disc = np.where(disc >= 0)

    t1 = np.zeros((len(disc), 3))
    t2 = np.zeros((len(disc), 3))

    # For negative discriminant with absolute value > 1e-6
    t1[small_disc] = np.zeros((len(small_disc), 3))
    t2[small_disc] = np.zeros((len(small_disc), 3))

    # For negative discriminant with absolute value < 1e-6
    t1[negative_disc] = (-g1[negative_disc])[:, None] * vij[negative_disc] + (2 * g0[negative_disc])[:, None] * vik[negative_disc]
    t2[negative_disc] = t1[negative_disc]

    # For positive discriminant
    t1[large_disc] = (-g1[large_disc] + np.sqrt(disc[large_disc]))[:, np.newaxis] * vij[large_disc] + (2 * g0[large_disc])[:, np.newaxis] * vik[large_disc]
    t2[large_disc] = (-g1[large_disc] - np.sqrt(disc[large_disc]))[:, np.newaxis] * vij[large_disc] + (2 * g0[large_disc])[:, np.newaxis] * vik[large_disc]

    # Normalize
    t1[negative_disc] /= np.linalg.norm(t1[negative_disc], axis=1)[:, None]
    t2[negative_disc] /= np.linalg.norm(t2[negative_disc], axis=1)[:, None]

    t1[large_disc] /= np.linalg.norm(t1[large_disc], axis=1)[:, None]
    t2[large_disc] /= np.linalg.norm(t2[large_disc], axis=1)[:, None]
    

    # Combine t1 and t2 for positive discriminant
    return  barycenters, t1, t2

In [10]:
torsal_dir_vec(tv, tf, e_i)

(array([[0.33333333, 0.33333333, 0.33333333]]),
 array([[ 0.78634314, -0.58356157, -0.20278157]]),
 array([[-0.32951142, -0.48221158,  0.81172299]]))

In [16]:
tors, cos_tors = torsal_directions(tv, tf, e_i)
print(tors)
print(np.arccos(cos_tors)*180/np.pi)

[[-0.32951142 -0.48221158  0.81172299]
 [ 0.78634314 -0.58356157 -0.20278157]]
[89.12199344]


In [10]:


tpos = open(os.path.join( out_path, "torsal_pos_"+str(k)+".dat"), "w")
tdir = open(os.path.join( out_path, "torsal_dir_nor_"+str(k)+".dat"), "w")

t_mesh = Mesh()
t_mesh.make_mesh(tv, tf)

inner_faces = t_mesh.inner_faces()

for ii in range(len(inner_faces)):
    i = inner_faces[ii]
    tpos.write(str(barycenters[i][0]) + " " + str(barycenters[i][1]) + " " + str(barycenters[i][2]) + "\n")
    tdir.write(str(torsal_dir[i][0]) + " " + str(torsal_dir[i][1]) + " " + str(torsal_dir[i][2]) + " " + str(torsal_dir[i][3]) + " " + str(torsal_dir[i][4]) + " " + str(torsal_dir[i][5]) + "\n")

tpos.close()
tdir.close()

igl.write_triangle_mesh(os.path.join( out_path, "tri_"+str(k)+".obj"), tv, tf)

Discriminant is negative for face  [124 430 359]  with value  -1.2455330902301411e-06 .
Discriminant is negative for face  [174 226 350]  with value  -1.439082891928254e-06 .
Discriminant is negative for face  [341 459  18]  with value  -1.4486609963626235e-05 .
Discriminant is negative for face  [176 425 285]  with value  -2.3612292246611834e-06 .
Mesh Data Structure: |V| = 469, |F| = 858, |E| = 1326


True

In [20]:
# Initialize polyscope
ps.init()


# Register a Mesh
v_tmesh = ps.register_surface_mesh("Mesh", tv, tf, smooth_shade=True)
ps.register_surface_mesh("Sphere Centers Mesh", h_pts, dual_faces, smooth_shade=True, edge_color=[0.8,0.5,0.5], edge_width=0.1)

# Draw circumcenter axis
# Register a point cloud
#v_cc = ps.register_point_cloud("Circumcenter ", tv, radius=0.01)

#print("ei :", e_i.shape)
#print("ct :", ct.shape)
# basic visualization
v_tmesh.add_vector_quantity("Axis", e_i, defined_on='vertices', enabled=True, radius=0.0001, length=5, color=(0.8, 0.0, 0.2))


# View the point cloud and mesh we just registered in the 3D UI
ps.show()

# Optimization 

### Load data

In [3]:
# Define paths
dir_path = os.getcwd()
data_path = dir_path+"/approximation/data/" # data path
out_path = dir_path+"/outputs/" # output path

# Data of interest
k = 2

# Init data files
file_pts = open(os.path.join( out_path, "points_"+str(k)+".dat"), "w")
ref = open(os.path.join( out_path, "init_directions_"+str(k)+".dat"), "w")

# Load M mesh (centers of sphere mesh)
mv, mf = igl.read_triangle_mesh( os.path.join(data_path ,"centers.obj") ) 

# Load test mesh
tv, tf = igl.read_triangle_mesh(os.path.join(data_path,  "test_remeshed_"+str(k)+".obj"))

# Create dual mesh
tmesh = Mesh()
tmesh.make_mesh(tv,tf)

# Get inner vertices
inner_vertices = tmesh.inner_vertices()

# Get vertex normals for test mesh
e_i = igl.per_vertex_normals(tv, tf)

# Fix normal directions
signs = np.sign(np.sum(e_i * ([0,0,1]), axis=1))
e_i = e_i * signs[:, None]

# Compute circumcenters and axis vectors for each triangle
p1, p2, p3 = tv[tf[:, 0]], tv[tf[:, 1]], tv[tf[:, 2]]

ct, rt, nt = circle_3pts(p1, p2, p3)

# Dual topology 
dual = tmesh.vertex_ring_faces_list()

# Dual topology without outer faces
dual_faces = [dual[vertex] for vertex in inner_vertices ]

# Create hexagonal mesh                            
h_pts = np.empty((len(tf), 3), dtype=np.float64)
center = vd.Mesh((mv, mf), alpha = 0.9, c=[0.4, 0.4, 0.81])

# Intersect circumcircle axis with center mesh
for i in range(len(tf)):
    # Get points on circumcircle axis
    p0  = ct[i] - 10*nt[i]
    p1  = ct[i] + 10*nt[i]
    
    # Get intersection points
    h_pts[i,:] = np.array(center.intersect_with_line(p0, p1)[0])

## Init Optimization

In [3]:
# tv test
tv = np.array([
    [0,0,1],
    [1,0,0],
    [0,1,0],
    ])

# tf test
tf = np.array([
    [0,1,2]
    ])

# e_i test
e_i = np.array([
    [0,0,0.2],
    [0,0.4,0.4],
    [0.5,0.5,0.5],
    ])

e_i = e_i / np.linalg.norm(e_i, axis=1)[:, None]

# Compute the directions at the barycenters
ec = np.sum( e_i[tf], axis = 1) / 3

# Compute the norms of ec
#nc = np.linalg.norm(ec, axis=1)

# # Compute the edge vectors per each face
vi, vj, vk = tv[tf[:,0]], tv[tf[:,1]], tv[tf[:,2]]


# # Compute the edge vectors per each face
vij = vj - vi
vik = vk - vi

# Set up X 
#X[:3*self.nV] = V.flatten()

eij = e_i[tf[:,1]] - e_i[tf[:,0]]
eik = e_i[tf[:,2]] - e_i[tf[:,0]]

# A = [vij, eik, ec] + [eij, vik, ec], where [ , , ] denotes determinant
# A = det1 +  det2
eikXec = np.cross(eik, ec)
vikXec = np.cross(vik, ec)

det1 = np.sum(vij*eikXec, axis=1)
det2 = np.sum(eij*vikXec, axis=1)

# b = [eij, eik, ec]  c = [vij, vik, ec]

b = np.sum(eij*eikXec, axis=1)
c = np.sum(vij*vikXec, axis=1)

A = det1 + det2 

print(A**2 - 4*b*c - 1**2)

# variables = [e_i | A| delta]; e_i direction per vertex in T and A is one per each triangle in T, same for delta 
X = np.zeros(3*len(tv) + 2*len(tf) )

# Optimization
X[:3*len(tv)] = e_i.flatten()


# Init constraints ---------------------------------------------
# # Init LineCong
#linecong = LineCong()
# X variables, e_i dim, pts in hexagonal mesh, faces in hexagonal mesh, inner vertices indices.
#linecong.initialize_constraint(X, len(tv), h_pts, dual, inner_vertices)

# # Init Hyperbolic
hyp = HyperbolicLC()
X = hyp.initialize_constraint(X, tv, tf, e_i, 1)


# Init optimizer
opt = Optimizer()
opt.initialize_optimizer(X)

# Compute J, r for each constraint
#linecong.compute(inner_vertices, dual, X)

# Add constraints  
#opt.add_constraint(linecong)
time_opt = []

for i in range(20):

    # Take time
    start = time.time()
    hyp.compute(X, tf)

    opt.add_constraint(hyp)

    # Optimize
    opt.optimize("LM")
    end = time.time()

    #print(f"delta : {opt.X[-1]}")

    time_opt.append(end - start)


opt.print_log()

#print(f"time:\n {time_opt}")

e_i = opt.X[:3*len(tv)].reshape(-1,3)

print(np.linalg.norm(e_i, axis=1))

eij = e_i[tf[:,1]] - e_i[tf[:,0]]
eik = e_i[tf[:,2]] - e_i[tf[:,0]]


ec = np.sum( e_i[tf], axis = 1) / 3
# A = [vij, eik, ec] + [eij, vik, ec], where [ , , ] denotes determinant
# A = det1 +  det2
eikXec = np.cross(eik, ec)
vikXec = np.cross(vik, ec)

det1 = np.sum(vij*eikXec, axis=1)
det2 = np.sum(eij*vikXec, axis=1)

# [vij, vik, ec] = det1 
vikXec = np.cross(vik, ec)
detA = np.sum(vij*vikXec, axis=1)

# [eij, eik, ec] = det2
eikXec = np.cross(eik, ec)
detC = np.sum(eij*eikXec, axis=1)
# b = [eij, eik, ec]  c = [vij, vik, ec]

A = det1 + det2 

Ac = opt.X[3*len(tv):3*len(tv)+len(tf)]

print(f"Disc f: {A**2 - 4*b*c} \t delta: { opt.X[-1]} \tenergy: {Ac**2 - 4*detA*detC - opt.X[3*len(tv) + len(tf):]**2}")

print(f" real A : {A} \t opt A : {Ac}")

print(f" step 5: {opt.X[:5]}")
# print(f" step 5 delta: {opt.X[-5:]}")
 

[1.42080693]
      Energy
0   2.018692
1   0.843477
2   0.342537
3   0.135813
4   0.052959
5   0.020466
6   0.009907
7   0.004795
8   0.002323
9   0.001127
10  0.000548
11  0.000315
12  0.000181
13  0.000104
14  0.000060
15  0.000034
16  0.000022
17  0.000015
18  0.000010
19  0.000006
[0.86882949 0.860683   0.84666238]
Disc f: [2.41066797] 	 delta: 1.0611835000081211 	energy: [0.00197161]
 real A : [0.39208101] 	 opt A : [0.39167843]
 step 5: [-0.04622534  0.00951205  0.86754678  0.01982813  0.58210704]


In [5]:
print(opt.X[-5:])
opt.print_log()

[0.9962556  0.99625561 0.99625561 0.99625561 0.99625561]
         Energy
0    858.354786
1    860.535232
2    869.912134
3    940.831957
4  84358.007391


## Minimize Library test

In [ ]:
from scipy import optimize


def energy(x0, ei_dim, cicj, dual_faces):

    # energy \sum_{f \in F} \sum_{cj,ci \in E(f)} || e_f (cj - ci)  ||^2
    cf = dual_faces
    
    # Init energy value
    total_energy = 0

    # Get directions
    ei = x0.reshape(ei_dim, 3)

    # Loop over faces
    for f in range(len(cf)):
        # Define Jacobian
        diff = np.dot(cicj[f], ei[f])

        # Define residual
        total_energy += np.sum( diff**2, axis=0)
    
    diff2 = np.sum(ei * ei, axis=1) - 1

    total_energy += np.sum(diff2**2, axis=0)

    return total_energy

# Define paths
dir_path = os.getcwd()
data_path = dir_path+"/approximation/data/" # data path
out_path = dir_path+"/outputs/" # output path

# Data of interest
k = 3

# Load M mesh (centers of sphere mesh)
mv, mf = igl.read_triangle_mesh( os.path.join(data_path ,"centers.obj") ) 
center = vd.Mesh((mv, mf), alpha = 0.9, c=[0.4, 0.4, 0.81])


# Load test mesh
tv, tf = igl.read_triangle_mesh(os.path.join(data_path,  "test_remeshed_"+str(k)+".obj"))

# Create test mesh
test_mesh =  vd.Mesh((tv, tf), alpha = 0.8)

# Draw edges Triangular mesh
edges = test_mesh.clone().lw(1.5).wireframe().flat().c('k').alpha(0.5)

# Create dual mesh
tmesh = Mesh()
tmesh.make_mesh(tv,tf)
# Get inner vertices
inner_vertices = tmesh.inner_vertices()
# Get outer vertices
outer_vertices = tmesh.boundary_vertices()

# Get vertex normals for test mesh
e_i = igl.per_vertex_normals(tv, tf)

# Fix normal directions
signs = np.sign(np.sum(e_i * ([0,0,1]), axis=1))
e_i = e_i * signs[:, None]

# Compute circumcenters and axis vectors for each triangle
p1, p2, p3 = tv[tf[:, 0]], tv[tf[:, 1]], tv[tf[:, 2]]

ct, rt, nt = circle_3pts(p1, p2, p3)

# Dual topology 
dual = tmesh.dual_top()

# Dual topology without outer faces
dual_faces = [dual[vertex] for vertex in inner_vertices ]

# Create hexagonal mesh                            
h_pts = np.empty((len(tf), 3), dtype=np.float64)

# Intersect circumcircle axis with center mesh
for i in range(len(tf)):
    # Get points on circumcircle axis
    p0  = ct[i] - 10*nt[i]
    p1  = ct[i] + 10*nt[i]
    
    # Get intersection points
    h_pts[i,:] = np.array(center.intersect_with_line(p0, p1)[0])

# Compute cij
cij = []
# Loop over faces
for f in range(len(dual_faces)):
    # Get face
    face = dual_faces[f]

    # Get vertices
    v0 = h_pts[face]
    v1 = np.roll(h_pts[face], -1, axis=0)
 
    cicj = (v1 - v0)/np.linalg.norm(v1 - v0, axis=1)[:, None]
    # Define direction
    cij.append(cicj)

dim = len(inner_vertices)


opt = optimize.minimize(energy, e_i[inner_vertices].flatten(), args=(dim, cij, dual_faces), options={'disp': True})


In [ ]:
e_i = opt.x.reshape(-1,3)

minfile = open(os.path.join( out_path, "min_directions_"+str(k)+".dat"), "w")

for v  in range(len(tmesh.inner_vertices())):   
    minfile.write(str(e_i[v][0]) + " " + str(e_i[v][1]) + " " + str(e_i[v][2]) + "\n")
minfile.close()



### Test Circumcircle

In [ ]:

# Get a list of random points
#p = np.random.rand(10,3)

p1 = np.random.rand(10,3)
p2 = np.random.rand(10,3)
p3 = np.random.rand(10,3)

c, rad, n = circle_3pts(p1,p2,p3)
print(f"centers: {c}\t rad: {rad}\t n: {n}")
circles = []
for ci in range(len(c)):
    print(f"centers: {c[ci]}\t rad: {rad[ci]}\t n: {n[ci]}")
    if ci%2 == 0:
        circles.append( vd.Circle(c[ci], r=rad[ci], c='red', alpha = 0.5).orientation(n[ci])) 
    else:
        circles.append( vd.Circle(c[ci], r=rad[ci], c="green", alpha = 0.5).orientation(n[ci])) 
pts1 = vd.Points(np.array( np.vstack((p1, p2, p3))), r = 10, c = 'black')
#pts2 = vd.Points(np.array([p1[1], p2[1], p3[1]]), r = 10, c = 'green')

vd.show(pts1,*circles)


## Sample Planarity Opt

In [ ]:
# Create four quads in 3D that merge in a vertex
v = np.array(
    [
        [ 0.01,  0.01,  0.8],
        [ 1.01,  0.03,  0.01],
        [-1.02,  0.02,  0.01],
        [ 0.01,  1.1, -0.2],
        [ 0.01, -1.3, -0.3],
        [-1.02,  1.01,  0.1],
        [ 1.01,  1.02,  0.2],
        [-1.04, -1.03, -0.3],
        [ 1.05, -1.04,  0.1],
    ]
   )
fcs = np.array([[0, 1, 6, 3], [2, 0, 3, 5], [7, 4, 0, 2], [4, 8, 1, 0]])

# Make mesh
m = Mesh()
m.make_mesh(v, fcs)

mesh1 = vd.Mesh((v, fcs), alpha = 0.8, c='r')

X = np.zeros((3*m.V+3*m.F), dtype=np.float64)

X[:3*m.V] = m.vertices.flatten()

# Init constraints
planarity = Planarity()
planarity.initialize_constraint(m, X)


# init optimizer
opt = Optimizer()

opt.initialize_optimizer(X)

for i in range(10):

    # Compute J, r for each constraint
    planarity.compute(m, X)
    
    # Add constraints  
    opt.add_constraint(planarity)
    opt.optimize("LM")
 

mesh2 = vd.Mesh((opt.X[:3*m.V].reshape(m.V,3),  fcs), alpha = 0.9, c='b')

print(opt.energy)

vd.show(mesh1, mesh2)



In [25]:

v = np.array(
    [
        [ 0.01,  0.01,  0.8],
        [ 1.01,  0.03,  0.01],
        [-1.02,  0.02,  0.01],
        [ 0.01,  1.1, -0.2],
        [ 0.01, -1.3, -0.3],
        [-1.02,  1.01,  0.1],
        [ 1.01,  1.02,  0.2],
        [-1.04, -1.03, -0.3],
        [ 1.05, -1.04,  0.1],
    ]
   )
fcs = np.array([[0, 1, 6, 3], [2, 0, 3, 5], [7, 4, 0, 2], [4, 8, 1, 0]])

nv = np.array([[-0.08452795, -0.5184518 ,  0.1204968 ],
       [ 0.09325778, -0.5417252 , -0.14323919],
       [-0.39126414,  0.38199818,  0.21744937],
       [ 0.05301311,  0.4957555 , -0.02630325],
       [-0.04160952, -0.68063384,  0.11461049],
       [-0.64098644,  0.96492183,  0.3065665 ],
       [ 0.29607683,  0.33823755, -0.46029344],
       [-0.24634174, -0.29367885,  0.3622692 ],
       [ 0.5331171 , -1.4693466 , -0.43155265]]
       )


mesh1 = vd.Mesh((v, fcs), alpha = 0.8, c='r')
mesh2 = vd.Mesh((nv, fcs), alpha = 0.8, c='b')


vd.show(mesh1, mesh2)

Plot(antialias=True, axes=['x', 'y', 'z'], axes_helper=1.0, axes_helper_colors=[16711680, 65280, 255], backgro…

In [ ]:
v, f = igl.read_triangle_mesh("models/catenoid_def_1.obj")
mesh = om.read_trimesh("models/catenoid_def_1.obj")
mp.plot(v, f, c=v[:, 0])

In [ ]:
def iso_stereo(n, h):
    # Isotropic model stereographic projection
    # n: normal vector
    # h: distance center to plane
    # return point in I3

    # Concatenate n[1:2] and h
    return np.vstack((n[1:2],v))/(1+ n[2])

In [ ]:
a = np.array([[1, 2, 3],[5,4,2] , [9,7,2]])
b = np.array([19,22,89])
# Add b as a column to a
c = np.column_stack((a,b))
print(a[:, 0:2])

In [ ]:
# Get face normals
nf = igl.per_face_normals(v, f, np.array([0.0, 0.0, 0.0]))
# Get indices v1 of each face
iv1 = f[:, 0]
# Get vertices of idv1
v1 = v[iv1, :]
# Compute dot product of each face normal with v1
h = np.sum(nf * v1, axis=1)

# Get Isotropic point per face
nv = np.column_stack((nf[:, 0:2], h)) / (1 + nf[:, 2, None])

nf = np.empty((0, 3), dtype=np.int32)

for fi in range(len(f)):
    aux = np.empty((0, ), dtype=np.int32)
    for adf in mesh.ff(mesh.face_handle(fi)):
        aux = np.hstack((aux, [adf.idx()]))
    if len(aux) == 3:
        nf = np.vstack((nf, aux))

mp.plot(nv, nf[:2])

In [ ]:
from scipy.sparse.linalg import spsolve
from scipy.sparse import csr_matrix

v, f = igl.read_triangle_mesh("models/Hall.obj")

# Draw the mesh
n = igl.per_vertex_normals(v, f) * 0.5 + 0.5
c = np.linalg.norm(n, axis=1)
p = mp.plot(v, f, c, return_plot=True) # plot

# Compute Cuvature properties
v1, v2, k1, k2 = igl.principal_curvature(v, f)



# Compute focal surfaces
rho1 = 100
rho2 = 1/k2

step = 0.001

lamb = 0.1 * np.ones(v.shape[0], dtype=np.float64)

J = np.eye(v.shape[0], dtype=np.float64) 

# Precalculate intermediate states
vs = [v]
cs = [c]
for i in range(30):
    # Compute the gradient of the focal surface
    H = csr_matrix(J.T@J)
    b = - J.T@(lamb - rho1)
    delta = spsolve(H, b)
    lamb = lamb + step * delta
    # Update the mesh
    v = v + lamb[:,None]*n

    # Recompute the normals
    n = igl.per_vertex_normals(v, f) * 0.5 + 0.5
    c = np.linalg.norm(n, axis=1)
    # Add to the list
    # p.update_object(vertices=v, colors=c)
    vs.append(v)
    cs.append(c)
    

# Add interactive visulization
@mp.interact(level=(0, 9))
def mcf(level=0):
    p.update_object(vertices=vs[level], colors=cs[level])
    vs.append(v)
    cs.append(c)
p